with(document) {
write("<v:group id=\"group5\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect5\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img5\" name=\"PrtImgId\" src=\"../img/SWA7E00R311000K5351YDAD72.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p5_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:220px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>37<br>(1.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:13px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Unit: mm (in.)<br>R: Round<br>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("<p id=\"p5_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:609px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:609px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-MIDDLE FLOOR INSULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:1055px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>205 (8.07)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:822px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>240 (9.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:1055px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>91 (3.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:668px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>50<br>(2.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:668px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35<br>(1.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:1055px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p5_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:1080px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:683px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>115 (4.53) <br></b></nobr>");
write("</p>");
write("<p id=\"p5_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:646px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>490 (19.3)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:859px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>R15<br>(0.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:925px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>R20<br>(0.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:808px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>63 (2.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:668px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>39<br>(1.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:668px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>75<br>(3.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:668px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>86<br>(3.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:668px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90<br>(3.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:1055px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>64<br></b></nobr>");
write("</p>");
write("<p id=\"p5_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:1080px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:1055px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p5_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:1080px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:1055px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p5_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:1080px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:14px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT-MIDDLE FLOOR INSULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p5_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:104px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>528 (20.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:139px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>155 (6.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:354px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>φ64 (2.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>144 <br>(5.67)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>55<br>(2.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>50<br>(2.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:455px;top:90px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35 (1.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:255px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>φ40 (1.6)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>59<br>(2.3)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>86<br>(3.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:319px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>114<br></b></nobr>");
write("</p>");
write("<p id=\"p5_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:342px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4.49)<br></b></nobr>");
write("</p>");
write("<p id=\"p5_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>88<br>(3.5)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl5_1\" name=\"prt_bl\" class=\"drag\" from=\"208,837\" to=\"207,816\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"60\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_2\" name=\"prt_bl\" class=\"drag\" from=\"224,844\" to=\"223,810\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(2.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_3\" name=\"prt_bl\" class=\"drag\" from=\"208,759\" to=\"207,741\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"35\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_4\" name=\"prt_bl\" class=\"drag\" from=\"224,765\" to=\"223,731\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(1.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_5\" name=\"prt_bl\" class=\"drag\" from=\"208,796\" to=\"207,773\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"50\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_6\" name=\"prt_bl\" class=\"drag\" from=\"224,803\" to=\"223,767\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(2.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_7\" name=\"prt_bl\" class=\"drag\" from=\"319,901\" to=\"318,869\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(1.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_8\" name=\"prt_bl\" class=\"drag\" from=\"304,893\" to=\"303,874\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"35\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_9\" name=\"prt_bl\" class=\"drag\" from=\"208,893\" to=\"207,876\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"85\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_10\" name=\"prt_bl\" class=\"drag\" from=\"224,900\" to=\"223,873\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(3.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_11\" name=\"prt_bl\" class=\"drag\" from=\"319,851\" to=\"318,806\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(1.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_12\" name=\"prt_bl\" class=\"drag\" from=\"208,1009\" to=\"207,973\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"113\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_13\" name=\"prt_bl\" class=\"drag\" from=\"208,940\" to=\"207,916\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"35\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_14\" name=\"prt_bl\" class=\"drag\" from=\"224,946\" to=\"223,909\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(1.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_15\" name=\"prt_bl\" class=\"drag\" from=\"672,1017\" to=\"671,998\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"76\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_16\" name=\"prt_bl\" class=\"drag\" from=\"688,1022\" to=\"687,982\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(3.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_17\" name=\"prt_bl\" class=\"drag\" from=\"688,851\" to=\"687,816\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(1.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_18\" name=\"prt_bl\" class=\"drag\" from=\"689,809\" to=\"688,742\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"95 (3.7)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_19\" name=\"prt_bl\" class=\"drag\" from=\"303,843\" to=\"302,814\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"30\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_20\" name=\"prt_bl\" class=\"drag\" from=\"673,844\" to=\"672,825\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"45\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_21\" name=\"prt_bl\" class=\"drag\" from=\"777,999\" to=\"776,949\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"20 (0.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_22\" name=\"prt_bl\" class=\"drag\" from=\"725,926\" to=\"724,863\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"490 (19.3)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_23\" name=\"prt_bl\" class=\"drag\" from=\"666,411\" to=\"665,323\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"641 (25.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_24\" name=\"prt_bl\" class=\"drag\" from=\"611,233\" to=\"610,203\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"76\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_25\" name=\"prt_bl\" class=\"drag\" from=\"627,239\" to=\"626,201\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(3.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_26\" name=\"prt_bl\" class=\"drag\" from=\"239,250\" to=\"238,226\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_26\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"128\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_27\" name=\"prt_bl\" class=\"drag\" from=\"258,250\" to=\"257,215\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_27\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(5.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_28\" name=\"prt_bl\" class=\"drag\" from=\"258,305\" to=\"257,273\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_28\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(3.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_29\" name=\"prt_bl\" class=\"drag\" from=\"259,353\" to=\"258,321\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_29\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(3.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_30\" name=\"prt_bl\" class=\"drag\" from=\"628,510\" to=\"627,439\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_30\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"288 (11.3)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_31\" name=\"prt_bl\" class=\"drag\" from=\"435,515\" to=\"434,416\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_31\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"506 (19.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_32\" name=\"prt_bl\" class=\"drag\" from=\"408,516\" to=\"407,423\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_32\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"313 (12.3)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_33\" name=\"prt_bl\" class=\"drag\" from=\"258,492\" to=\"257,402\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_33\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"358 (14.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_34\" name=\"prt_bl\" class=\"drag\" from=\"716,234\" to=\"715,192\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_34\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"20 (0.8)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_35\" name=\"prt_bl\" class=\"drag\" from=\"240,353\" to=\"239,337\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_35\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"76\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_36\" name=\"prt_bl\" class=\"drag\" from=\"240,305\" to=\"239,291\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_36\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"79\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_37\" name=\"prt_bl\" class=\"drag\" from=\"626,324\" to=\"625,258\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_37\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"137 (5.39)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_38\" name=\"prt_bl\" class=\"drag\" from=\"611,380\" to=\"610,355\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_38\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"120\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_39\" name=\"prt_bl\" class=\"drag\" from=\"628,380\" to=\"627,343\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_39\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(4.72)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_40\" name=\"prt_bl\" class=\"drag\" from=\"226,1010\" to=\"225,974\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_40\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(4.45)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_41\" name=\"prt_bl\" class=\"drag\" from=\"363,1012\" to=\"362,936\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_41\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"153 (6.02)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl5_42\" name=\"prt_bl\" class=\"drag\" from=\"688,942\" to=\"687,871\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp5_42\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"137 (5.39)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:8.6pt;\"/>");
write("</v:line>");
write("</v:group>");
}