with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SWA7E40000000000000EBA310.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-94px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:546px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:900px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G601]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:750px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:590px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:676px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:676px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:676px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:676px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:676px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-37px;top:676px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-37px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:738px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:738px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-37px;top:738px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:546px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:546px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-48px;top:710px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-47px;top:816px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-37px;top:787px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:590px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:816px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:590px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:590px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:590px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:710px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:816px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:787px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:816px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:590px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:816px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:590px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:787px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:816px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:710px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G551<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:900px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G503]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:900px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G503]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:25px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:900px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G503]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-51px;top:900px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G503]<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:640px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FRONT <br>ACCESSORY <br>POWER SOCKET <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:640px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CONSOLE <br>ACCESSORY <br>POWER SOCKET <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:640px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>REAR <br>ACCESSORY <br>POWER SOCKET <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-24px;top:751px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FRONT <br>ACCESSORY <br>POWER <br>SOCKET<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:751px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CONSOLE <br>ACCESSORY <br>POWER <br>SOCKET<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:751px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>REAR <br>ACCESSORY <br>POWER <br>SOCKET<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-543px;top:690px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>VANITY <br>MIRROR <br>LIGHT <br>(2 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-188px;top:760px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:646px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>REAR <br>WINDOW <br>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-121px;top:645px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CIGARETTE <br>LIGHTER <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:465px;top:515px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-44px;top:515px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>68<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-26px;top:487px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:515px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>69<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:515px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>61<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:487px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:515px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>67<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:487px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:488px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:489px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.28 (20 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:489px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.31 (20 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:489px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.34 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-59px;top:489px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.29 (20 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:450px;top:482px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER <br>RELAY <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-1185px;top:20px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Wiper/Washers, Interior Lights, Cigarette Lighter, Accessory Power Sockets, Rear Window Defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:143px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:27px;top:122px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:120px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:141px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:131px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[    ] : RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:141px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:172px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:172px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: With sunshade<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:185px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: With navigation system and without sunshade<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:185px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:159px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:159px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:146px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: LHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:146px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:122px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*6 : With sunshade<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:115px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*5 : Without sunshade<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:87px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*1 : UNDER−DASH FUSE/RELAY BOX (With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:94px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX (Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:169px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:169px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>153<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:169px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:359px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:324px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:382px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:444px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G201<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:45px;top:217px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:217px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:217px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:444px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:246px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:246px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:382px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:306px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:246px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-81px;top:326px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-81px;top:366px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-93px;top:253px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:101px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:108px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-73px;top:339px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WINDSHIELD/<br>REAR WINDOW <br>WASHER MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-108px;top:146px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(5−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:264px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HEADLIGHT WASHER <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:335px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HEADLIGHT <br>WASHER <br>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:143px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.28 (30 A) <br>FUSE <br>(1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:82px;top:150px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:143px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.16 (10 A) <br>FUSE <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:122px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.16 (15 A) <br>FUSE <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-316px;top:136px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>REAR WINDOW <br>WIPER MOTOR <br>RELAY <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-237px;top:150px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(5−A)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}