with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:735px;\" coordsize=\"950,735\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:735px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E59G24100000000CAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:735px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:326px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>−99<br>(−1)<br>[−14]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:326px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:326px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>196<br>(2)<br>[28]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:552px;top:325px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3,138<br>(32)<br>[455]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:326px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>kPa<br>(kgf/cm<sup>2</sup>)<br>[psi]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:64px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4.575<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:214px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0.684<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:249px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0.425<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:261px;top:287px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0.2945<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:119px;top:72px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTPUT<br>VOLTAGE<br>(Vout)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:697px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Vcc 5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:697px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Vout<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:696px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:404px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C PRESSURE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}