with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:671px;\" coordsize=\"950,671\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:671px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SWA7E1PE10474000000CAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:671px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:42px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:281px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>LOCK-UP<br>SHIFT VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:455px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>LOCK-UP<br>CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:218px;top:501px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>RELIEF VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:539px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>ATF<br>COOLER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:455px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>COOLER<br>CHECK<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:370px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>TORQUE<br>CONVERTER<br>CHECK VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:560px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>REGULATOR<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:630px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>ATF PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:520px;top:173px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>A/T CLUTCH PRESSURE CONTROL SOLENOID VALVE A<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:443px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IDLER SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:454px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:465px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:477px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:485px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>FINAL DRIVE<br>GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:497px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>SECONDARY<br>SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:233px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:223px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:209px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:210px;top:268px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:303px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:303px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:304px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:304px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:304px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:304px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:271px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>91<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:271px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>94<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:271px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55'<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:400px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>97<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:400px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:400px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>96<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:400px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:432px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:433px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:445px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:435px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:400px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>90<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:436px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:433px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:507px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:508px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:547px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:544px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:593px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>99<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:527px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>92<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:528px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>95<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:561px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:560px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:396px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:414px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:420px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:431px;font-weight:normal;font-size:3.1pt;\">");
write("<nobr><b>HX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:116px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>SE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:156px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:156px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:133px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:103px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT SOLENOID VALVE E<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:461px;top:216px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:225px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:197px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>55<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:216px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:216px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>AX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:261px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>SHIFT VALVE A and D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:348px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>MANUAL VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:440px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:480px;font-weight:normal;font-size:5.0pt;\">");
write("<nobr><b>93<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}