with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\" coordsize=\"1900,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E50000000000000EBAD22.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1250px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VBU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:309px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:316px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:651px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:644px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1186px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1175px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1177px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>178<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1669px;top:108px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4 : R20A1 and R20A2 engines<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1669px;top:101px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3 : K24Z1 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1729px;top:124px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1354px;top:763px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>219<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1425px;top:763px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>218<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1425px;top:568px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>217<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1496px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>223<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1461px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>222<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1425px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>221<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1390px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>220<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1275px;top:300px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1347px;top:300px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1563px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>224<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1594px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>225<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1254px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>75<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1329px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>65<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:603px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>131<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:437px;top:603px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>186<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:301px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>65<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:457px;top:300px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>75<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>183<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>125<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1563px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1552px;top:536px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1505px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1470px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1598px;top:596px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1588px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1598px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1634px;top:596px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1623px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1634px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1590px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICROPHONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1567px;top:653px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ROOF CONSOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1623px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1623px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1587px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1587px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1547px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1547px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MIC IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1541px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1518px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1518px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SIG SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1456px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1456px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1492px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1492px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SIG−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1434px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1399px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1421px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ICON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1385px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MUTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1421px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1385px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1494px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1459px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1529px;top:425px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1384px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1418px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1250px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1261px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1337px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1325px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1294px;top:490px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1326px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1326px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1323px;top:576px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CABLE REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1306px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1423px;top:598px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1334px;top:673px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>180 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1336px;top:660px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>47 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1308px;top:665px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1306px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1295px;top:536px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1423px;top:744px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1434px;top:737px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1434px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1294px;top:504px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1294px;top:497px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>STRG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1306px;top:551px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1294px;top:616px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1306px;top:600px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1363px;top:737px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1352px;top:744px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1330px;top:478px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE  CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1592px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1603px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1572px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1560px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1591px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1591px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>OUT−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1560px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>OUT+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1560px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1157px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1172px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1168px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1158px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1156px;top:838px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1154px;top:844px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G502]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:880px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:849px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:947px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:947px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:916px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:916px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:982px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:982px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1013px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1013px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:847px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:977px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:938px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:966px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:966px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:927px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:927px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1017px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1002px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1002px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1002px;top:488px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:795px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:795px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:898px;top:795px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:938px;top:795px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:977px;top:795px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:924px;top:815px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:924px;top:808px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:964px;top:808px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:964px;top:815px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:815px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:808px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:808px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:815px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:808px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:815px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:205px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ANTENNA MAST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:838px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G504<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:740px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:516px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1669px;top:115px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[    ] : RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1729px;top:131px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:21px;font-weight:normal;font-size:8.8pt;\">");
write("<nobr><b>Audio System (Audioless), Hands Free Telephone Control Unit<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1669px;top:86px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:300px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1669px;top:93px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1838px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:302px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:622px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(Built in the <br>gauge control <br>module) <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:251px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:977px;top:251px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT REAR <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:911px;top:251px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT REAR <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:251px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1350px;top:783px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUDIO  <br>REMOTE <br>SWITCH <br>(20−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1270px;top:738px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HFT−VOICE <br>CONTROL SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1416px;top:533px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUDIO <br>REMOTE <br>SWITCH <br>(20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1421px;top:783px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUDIO <br>REMOTE <br>SWITCH <br>(20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1434px;top:718px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1368px;top:696px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>OFF <br>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1337px;top:696px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ON <br>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:302px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ECM/PCM <br>(4−D) <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:309px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:302px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.23 (10 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:302px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.34 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:622px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(DLC) <br>(4−D) <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1313px;top:302px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.34 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1242px;top:302px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.23 (10 A) <br>FUSE <br>(2−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1461px;top:302px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE <br>CONTROL UNIT (20−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1173px;top:309px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VBU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1010px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:913px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:889px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:975px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:944px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:955px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:924px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:991px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1022px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:878px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:323px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:980px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:656px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:656px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:656px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:967px;top:656px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:656px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1006px;top:532px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:851px;top:833px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUXILIARY JACK ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:967px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:845px;top:571px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[WHT]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:571px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1006px;top:611px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:926px;top:749px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:964px;top:757px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:757px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1006px;top:705px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:791px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:889px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:924px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:955px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1022px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:991px;top:290px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:886px;top:664px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[BLK]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:845px;top:664px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:664px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[YEL]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:965px;top:664px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[RED]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:749px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:749px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:749px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:967px;top:749px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:925px;top:757px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:663px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:359px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ANTENNA LEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ANTENNA SUBLEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:592px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(AM/FM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ANT +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642px;top:292px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AMPLIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:501px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:379px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:461px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SCTY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:478px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:563px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:502px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ILL−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ILL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:440px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:403px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:454px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSSOUT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}