with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:520px;\" coordsize=\"950,520\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:520px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40J36300000000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:520px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:40px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>: CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:441px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:147px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:112px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:489px;top:72px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE (TACH)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:122px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>F−CAN <br>TRANSCEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:193px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN <br>TRANSCEIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:285px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IMMOBILIZER− <br>KEYLESS CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:287px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HANDS FREE <br>TELEPHONE <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:423px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:167px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AUTOMATIC <br>LIGHTING/ <br>RAIN SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:416px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ADAPTIVE <br>FRONT LIGHTING <br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}