with(document) {
write("<v:group id=\"group14\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:591px;\" coordsize=\"950,591\">");
write("<v:rect id=\"rect14\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:591px;\">");
write("<img id=\"img14\" name=\"PrtImgId\" src=\"../img/SWA7E40A20300000000DBAD13.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:591px;border-color:#ffffff\">");
write("<p id=\"p14_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:92px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p14_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:76px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p14_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:397px;top:68px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p14_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:59px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p14_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:423px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p14_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:263px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p14_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:299px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p14_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:415px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p14_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:430px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p14_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:306px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p14_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:113px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p14_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:128px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p14_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:170px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p14_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:144px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p14_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:190px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p14_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:471px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p14_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:519px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p14_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:501px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p14_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:702px;top:94px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p14_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p14_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:598px;top:72px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p14_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:75px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p14_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:81px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p14_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:422px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p14_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:511px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p14_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:390px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JUNCTION<br>BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}