with(document) {
write("<v:group id=\"group11\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1055px;\" coordsize=\"950,1055\">");
write("<v:rect id=\"rect11\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1055px;\">");
write("<img id=\"img11\" name=\"PrtImgId\" src=\"../img/SWA7EF0A20300000000EAAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1055px;border-color:#ffffff\">");
write("<p id=\"p11_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:810px;top:230px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:343px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PGM-FI MAIN<br>RELAY 2<br>(FUEL PUMP)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:19px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p11_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:854px;top:66px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>STARTER<br>CUT RELAY<br>(ST CUT)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:165px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:148px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:156px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:168px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F8<br></b></nobr>");
write("</p>");
write("<p id=\"p11_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:175px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:188px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F10<br></b></nobr>");
write("</p>");
write("<p id=\"p11_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:195px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:207px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F11<br></b></nobr>");
write("</p>");
write("<p id=\"p11_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:215px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:235px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F24<br></b></nobr>");
write("</p>");
write("<p id=\"p11_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:255px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F30<br></b></nobr>");
write("</p>");
write("<p id=\"p11_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:262px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:275px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F25<br></b></nobr>");
write("</p>");
write("<p id=\"p11_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:282px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:314px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F29<br></b></nobr>");
write("</p>");
write("<p id=\"p11_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:353px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:361px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:393px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G12<br></b></nobr>");
write("</p>");
write("<p id=\"p11_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:400px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:433px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G20<br></b></nobr>");
write("</p>");
write("<p id=\"p11_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:439px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:472px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:479px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:492px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q5<br></b></nobr>");
write("</p>");
write("<p id=\"p11_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:499px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:511px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q9<br></b></nobr>");
write("</p>");
write("<p id=\"p11_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:565px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>E9<br></b></nobr>");
write("</p>");
write("<p id=\"p11_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:572px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:693px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:703px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p11_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:423px;top:657px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:623px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:631px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:659px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:667px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:695px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p11_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:703px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:731px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:738px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:623px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p11_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:23px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p11_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:24px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p11_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:23px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p11_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:23px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AC<br></b></nobr>");
write("</p>");
write("<p id=\"p11_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:48px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C36<br></b></nobr>");
write("</p>");
write("<p id=\"p11_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:66px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:107px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A44<br></b></nobr>");
write("</p>");
write("<p id=\"p11_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:125px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S-NET5V<br></b></nobr>");
write("</p>");
write("<p id=\"p11_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:147px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p11_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:164px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IMOFPR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:186px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A31<br></b></nobr>");
write("</p>");
write("<p id=\"p11_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:204px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SCS<br></b></nobr>");
write("</p>");
write("<p id=\"p11_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:226px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A40<br></b></nobr>");
write("</p>");
write("<p id=\"p11_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:243px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BKSW<br></b></nobr>");
write("</p>");
write("<p id=\"p11_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:57px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p11_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:81px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:80px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p11_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Z<br></b></nobr>");
write("</p>");
write("<p id=\"p11_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p11_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Y<br></b></nobr>");
write("</p>");
write("<p id=\"p11_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:729px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ST<br></b></nobr>");
write("</p>");
write("<p id=\"p11_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:659px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p11_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:695px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:731px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:810px;top:387px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:599px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(13)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:773px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p11_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:781px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:991px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FUEL PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p11_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:947px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p11_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:926px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:949px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p11_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:958px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p11_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:685px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUSES:<br>UNDER-HOOD <br>FUSE/RELAY BOX:<br>(1)No. 21 DBW (THROTTLE<br>ACTUATOR CONTROL) (15 A)<br>(2)No. 18 IG COIL (15 A)<br>(3)No. 19 FI MAIN (15 A)<br>(4)No. 11 +B LAF <br> (A/F SENSOR) (15 A)<br>(5)No. 15 OIL LVL (7.5 A)<br>(6)No. 2 IG MAIN (50 A)<br>(7)No. 23 BACK UP (10 A)<br>(8)No. 12 STOP, HORN (15 A)<br>(9)No. 1 MAIN FUSE (100 A)<br><br>UNDER-DASH FUSE/RELAY BOX:<br>(10)No. 3 ALTERNATOR (10 A)<br>(11)No. 2 FUEL PUMP (15 A)<br>(12)No. 36 IG2 HAC (A/C) (10 A)<br>(13)No. 10 METER (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p11_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:129px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>F15<br></b></nobr>");
write("</p>");
write("<p id=\"p11_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:136px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:465px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12P<br>JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p11_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:450px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p11_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:482px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p11_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:524px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p11_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:472px;top:322px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:519px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p11_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:570px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:466px;top:243px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p11_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:1021px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G603<br></b></nobr>");
write("</p>");
write("<p id=\"p11_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:373px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p11_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:816px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p11_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:839px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p11_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:810px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p11_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:830px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:857px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE PEDAL<br>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p11_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:821px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pedal pressed:closed<br>Brake pedal released:open<br></b></nobr>");
write("</p>");
write("<p id=\"p11_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:267px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p11_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:1014px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*1: A/T<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}