with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:719px;\" coordsize=\"950,719\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:719px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40G10100000000FEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:719px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>kPa<br>(kgf/cm<sup>2</sup>)<br> [psi]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:604px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:364px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:470px;top:633px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br>(68)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:633px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>25<br>(77)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:633px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br>(86)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:633px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>35<br>(95)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:633px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>°C<br>(°F)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:633px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>40<br>(104)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:152px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3,000<br>(30.6)<br>[435]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:590px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:454px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br>(50)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:302px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br>(68)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:153px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30<br>(86)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:55px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUMIDITY<br>LEVEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:99px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:634px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:687px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:604px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:137px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:303px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2,000<br>(20.4)<br>[290]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:454px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1,000<br>(10.2)<br>[145]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:77px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>400<br>(4.1)<br>[58]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:378px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>0<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:533px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>TEMPERATURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:432px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DELIVERY<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:295px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:45px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>°C<br>(°F)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:88px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>kPa<br>(kgf/cm<sup>2</sup>)<br> [psi]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:228px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>200<br>(2.0)<br>[29]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:196px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:287px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:214px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>80 %<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:767px;top:359px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 %<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}