with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:952px; height:783px;\" coordsize=\"952,783\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:952px;height:783px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00D14300014711LAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:952px;height:783px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:542px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PAD RETAINERS<br></b>Replacing brake pads,<br>replace its as new one.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:163px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>BRAKE HOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:734px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>BRAKE PADS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:92px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>BANJO BOLT<br>35 N·m <br>(3.6 kgf·m, 26 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:405px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PISTON SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:456px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PIN BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:295px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>SEALING WASHERS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:141px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>BLEEDER SCREW<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:217px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>CALIPER BODY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:289px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PISTON ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:433px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>CALIPER BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:436px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>CALIPER PINS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:647px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>10 x 1.25 mm<br>55 N·m <br>(5.6 kgf·m, 41 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:26px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>: Rubber grease (0204181122)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:60px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>: Seal grease (0204181201)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:364px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>30 N·m <br>(3.1 kgf·m, <br>22 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:126px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PIN BOOT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:210px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>CALIPER PIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:720px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>WEAR INDICATOR<br></b>Install inner pad with its <br>wear indicator downward.<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:339px;font-weight:normal;font-size:8.7pt;\">");
write("<nobr><b>PIN<br>BUSH<br></b>Replace.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}