with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R51100000000YDAD10.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:49px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:463px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF FRONT<br>FRAME UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:129px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF SIDE<br>FRAME UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:85px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF SIDE<br>FRAME UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:549px;top:395px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROOF<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:509px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER<br>GUTTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:459px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TAILGATE<br>HINGE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:375px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Glass Roof Model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:667px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KE, KG, and KS Models<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:763px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT JACK<br>UP BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:883px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:789px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701px;top:1022px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT<br>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:742px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR JACK<br>UP BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:930px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE <br>SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:701px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL REINFORCEMENT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:1056px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Do not apply the sealer<br>to the water drain hole.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}