with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\" coordsize=\"1900,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E50000000000000EBAD16.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1238px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1207px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1176px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1178px;top:643px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>205<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1209px;top:643px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>206<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1240px;top:643px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>207<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1136px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1109px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1083px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1297px;top:692px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1297px;top:685px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1666px;top:130px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4 : R20A1 and R20A2 engines<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1666px;top:123px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3 : K24Z1 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1725px;top:168px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1666px;top:109px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1666px;top:116px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1677px;top:142px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: VSA OFF SWITCH 5P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1677px;top:156px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: VSA OFF SWITCH 17P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1283px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1283px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1297px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1289px;top:643px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>131<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1029px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1056px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1083px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1109px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1136px;top:612px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1040px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>35<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1067px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1094px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1120px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1147px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>32<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1027px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1054px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SVCC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1082px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ST−Z<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1109px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ST−B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1135px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ST−A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1040px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1147px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1120px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1094px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1067px;top:627px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1048px;top:660px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>STEERING ANGLE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:567px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:567px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:567px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:878px;top:252px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:252px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:971px;top:643px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:961px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:996px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:891px;top:643px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:881px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:916px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:811px;top:643px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:618px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:643px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>IC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:935px;top:252px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:927px;top:465px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:740px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G202<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>46<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>+B MOT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:630px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>43<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RL−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RL+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:824px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RR+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:836px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RR−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:950px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:961px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:944px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FR−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:985px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:996px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>29<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:984px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FR+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:904px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FL+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:916px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:906px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FL−GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:881px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:870px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>+B SOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>44<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:913px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:910px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:921px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:911px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1036px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1049px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1038px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1040px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>127<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:992px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>126<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:989px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1001px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>39<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:987px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:667px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:667px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875px;top:667px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:953px;top:667px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:680px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1668px;top:142px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1668px;top:156px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1105px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRK LAMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1125px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>37<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1114px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1116px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>111<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1165px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>112<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1162px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1173px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1154px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRK DIAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1515px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1528px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1517px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1519px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>126<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1568px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>127<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1566px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1577px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1564px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1470px;top:415px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1479px;top:401px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1469px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1472px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>54<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1491px;top:252px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1517px;top:520px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1518px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1516px;top:740px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G552<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1528px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:740px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>193<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:341px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:280px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:252px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:603px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:451px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:643px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>186<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:399px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:399px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: 10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:385px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:385px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:385px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:385px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: 4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:399px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:399px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:549px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:549px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: 11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:536px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:536px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:470px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>VSA System<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1838px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:463px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA <br>OFF <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:663px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(Built in the <br>gauge control <br>module) <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:253px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:246px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GAUGE <br>CONTROL <br>MODULE <br>(8−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1488px;top:460px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YAW RATE−LATERAL <br>ACCELERATION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1524px;top:256px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE (7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1460px;top:253px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.4 (7.5 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1125px;top:256px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRAKE LIGHT <br>RELAY (3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:905px;top:253px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.4 (7.5 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:996px;top:256px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE (7−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:253px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.3 (ABS MTR) (40 A) <br>FUSE <br>(1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:253px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.3 (ABS FSR) (20 A) <br>FUSE <br>(1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1280px;top:663px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(DLC) <br>(4−D) <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1187px;top:667px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ADAPTIVE <br>FRONT LIGHTING <br>CONTROL UNIT <br>(10−B)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}