with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00K80100081110FAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:56px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL-GND (PUR)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:172px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR-GND<br>(PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:180px;top:172px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR +B (LT GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:148px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL +B (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:192px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR +B (GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:56px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RL +B (YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:78px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FL-GND (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT 46P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:287px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:53px;top:78px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RR-GND (BLU)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}