with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1055px;\" coordsize=\"950,1055\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1055px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40A18400025601KBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1055px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:801px;top:50px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MUFFLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:690px;top:287px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:290px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELF-LOCKING NUT<br>10 x 1.25 mm<br>33 N·m <br>(3.4 kgf·m, 25 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:805px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:863px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CATALYTIC CONVERTERTIGHTENING <br>SEQUENCE<br>SELF-LOCKING NUT<br>10 x 1.25 mm<br>33 N·m (3.4 kgf·m, 25 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:443px;top:400px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST PIPE B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:735px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:830px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKETS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:251px;top:100px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEAT SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:544px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CATALYTIC<br>CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:878px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:858px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:615px;top:933px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:51px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6 x 1.0 mm<br>9.8 N·m <br>(1.0 kgf·m, 7.2 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:689px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WARM-UP <br>CATALYTIC<br>CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:162px;top:876px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WARM-UP <br>CATALYTIC<br>CONVERTER<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:951px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:967px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b>Tighten the bolts in steps,<br>altemating side-to-side.<br></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:427px;top:668px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXHAUST <br>PIPE A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:475px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE: Use new gaskets and self-locking nuts when reassembling.<br></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:325px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8 x 1.25 mm<br>22 N·m <br>(2.2 kgf·m, 16 lbf·ft)<br></b>Tighten the nuts in steps,<br>altemating side-to-side.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}