with(document) {
write("<v:group id=\"group12\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\" coordsize=\"950,799\">");
write("<v:rect id=\"rect12\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img12\" name=\"PrtImgId\" src=\"../img/SWA7E40A20300000000DBAD11.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p12_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:80px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p12_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:64px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p12_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:52px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p12_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p12_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p12_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:22px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p12_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:78px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p12_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:474px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p12_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:575px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p12_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:668px;top:740px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p12_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:755px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p12_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:760px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p12_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:760px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p12_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:758px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p12_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:755px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p12_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:741px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p12_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:671px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p12_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p12_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:549px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p12_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:678px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE OIL LEVEL<br>SENSOR SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p12_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}