with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:336px;\" coordsize=\"475,336\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:336px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E58K711000Y2983FAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:336px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT 36P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:33px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:286px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RECIRCULATION AIR MIX CONTROL MOTOR 7P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:302px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:116px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:116px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:203px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:255px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}