with(document) {
write("<v:group id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\" coordsize=\"950,799\">");
write("<v:rect id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/SWA7EF0A20300000000DBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:13px;top:518px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JUNCTION BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:742px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:123px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:89px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:67px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:50px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:216px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:430px;top:714px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:558px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:602px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:581px;top:669px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:642px;top:638px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:697px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:882px;top:366px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:564px;top:42px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:741px;top:84px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:875px;top:295px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}