with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:497px;\" coordsize=\"475,497\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:497px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E30A18316617502KBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:497px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:55px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Main <br>journal <br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:132px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:183px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:234px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:286px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:337px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:388px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:424px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller<br>main<br>journal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:424px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller<br>bearing<br>(Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Larger crank bore<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1 or <br>A or I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2 or <br>B or II<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3 or <br>C or III<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:42px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4 or <br>D or IIII<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:84px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller bearing (Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:386px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Blue<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:129px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:232px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:328px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:386px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:232px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:276px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:335px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:181px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:225px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:130px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:173px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:233px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:284px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:395px;top:327px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black/<br>Blue<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:26px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Crank <br>bore <br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:123px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink/<br>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:130px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:182px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:175px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink/<br>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:335px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:386px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:380px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black/<br>Blue<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}