with(document) {
write("<v:group id=\"group9\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1040px;\" coordsize=\"950,1040\">");
write("<v:rect id=\"rect9\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1040px;\">");
write("<img id=\"img9\" name=\"PrtImgId\" src=\"../img/SWA7E56J54260400000EAAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1040px;border-color:#ffffff\">");
write("<p id=\"p9_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-1293px;top:292px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b><br></b></nobr>");
write("</p>");
write("<p id=\"p9_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:44px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2 : Without HID<br></b></nobr>");
write("</p>");
write("<p id=\"p9_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:477px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.17 (15 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:488px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.17 (10 A)*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:445px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.16 (10 A)*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:434px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.16 (15 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:241px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.21 (30 A)*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:252px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.21 (20 A)*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p9_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:32px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*1 : With HID<br></b></nobr>");
write("</p>");
write("<p id=\"p9_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:968px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:981px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.71 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:997px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:997px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight washer control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:919px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p9_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:900px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:479px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:400px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:321px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:696px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AFS/CMBS OFF switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA OFF switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:868px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU (+B HAZARD)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Parking/back−up sensor switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:554px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Steering switches light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:568px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Seat heater switches light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:725px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:725px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof switch light (With sunroof)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:754px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Microphone (With navigation)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:475px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight washer control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p9_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:288px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU (+B RR FOG)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:214px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:174px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.19 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:42px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p9_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:189px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU (+B SMALL)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:138px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.18 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:125px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p9_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:209px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.20 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:83px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p9_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:178px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:142px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:154px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU (+B H/L HI)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:256px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:268px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU (+B H/L LO)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p9_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:304px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlight (high beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlight (high beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:382px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:367px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.13 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:503px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:504px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left headlight (low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right headlight (low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:461px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:539px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p9_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:768px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:524px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.14 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:752px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.15 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:768px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:582px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Glove box light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:611px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HVAC/climate control unit light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:625px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Hazard warning switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:739px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunshade switch light (With sunshade)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:796px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p9_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:811px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p9_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:825px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:243px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p9_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:596px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Audio unit light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:639px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight leveling switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror switch light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:796px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p9_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:782px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:839px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:856px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:839px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p9_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:62px;top:790px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p9_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:748px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.10 (15 A) FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:655px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Park−pin switch/ <br>A/T gear position indicator panel light<br></b></nobr>");
write("</p>");
write("<p id=\"p9_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:30px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.4 (H/L) <br>(50 A) FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:945px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AUXILIARY <br>UNDER−DASH FUSE HOLDER<br></b></nobr>");
write("</p>");
write("<p id=\"p9_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:281px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay <br>box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:359px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay <br>box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:438px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay <br>box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p9_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:516px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay <br>box socket)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}