with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:904px;\" coordsize=\"950,904\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:904px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SWA7E54J54260400000EAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:904px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:57px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2 : R20A1 and R20A2 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:45px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*1 : K24Z1 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:220px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:232px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/WHT*<sup>1</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:192px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:332px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Starter solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:283px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Transmission range switch<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:474px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.23 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:292px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Starter solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:400px;top:225px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:732px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:721px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:667px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.35 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Key interlock solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:436px;top:682px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:617px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.34 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:632px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Audio unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:647px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Hands Free Telephone control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:588px;top:661px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Accessory power socket relays<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:555px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:603px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:50px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:512px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ACC <br>(IGNITION <br>SWITCH)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:241px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ST <br>(IGNITION <br>SWITCH)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:316px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>STARTER <br>CUT RELAY<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}