with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:751px;\" coordsize=\"950,751\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:751px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40E3415033911FMFAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:751px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:157px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST/2ND SHIFT FORK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3RD/4TH SHIFT FORK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5TH/6TH SHIFT FORK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:281px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5TH/6TH<br>SHIFT PIECE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:352px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5 x 22 mm/3 x 22 mm<br>SPRING PIN<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:508px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1.6−2.4 mm<br>(0.063−0.094 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:503px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PIN DRIVER, 5 mm<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:354px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REVERSE SHIFT<br>PIECE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}