with(document) {
write("<v:group id=\"group15\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:879px;\" coordsize=\"950,879\">");
write("<v:rect id=\"rect15\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:879px;\">");
write("<img id=\"img15\" name=\"PrtImgId\" src=\"../img/SWA7E80A20300000000DBAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:879px;border-color:#ffffff\">");
write("<p id=\"p15_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:115px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p15_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:90px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p15_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:317px;top:70px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p15_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:421px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p15_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:150px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p15_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:781px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p15_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:713px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p15_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:596px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p15_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:786px;top:671px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p15_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p15_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:835px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p15_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:826px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p15_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:67px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p15_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:64px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p15_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:43px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p15_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:47px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p15_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:54px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p15_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:822px;top:140px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p15_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:525px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STARTER<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p15_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:536px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p15_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p15_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:864px;top:431px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}