with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:401px;\" coordsize=\"475,401\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:401px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E1PK771000U0122FAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:401px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:166px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CAN L (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>PCM CONNECTOR A (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:166px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CAN H (WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:330px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CAN H (WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:263px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CAN L (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:208px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>VSA MODULATOR-<br>CONTROL UNIT <br>CONNECTOR <br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:371px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:189px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Terminal side of<br>female terminals<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}