with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:447px;\" coordsize=\"950,447\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:447px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E00D52100000000CAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:447px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LEFT-REAR<br>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:141px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RIGHT-REAR<br>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:370px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LEFT-FRONT<br>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RIGHT-FRONT<br>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Select Low<br>Speed Wheel<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:63px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Vehicle Speed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:141px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Drive<br>Solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:141px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RIGHT-REAR<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LEFT-REAR<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:835px;top:293px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RIGHT-FRONT<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LEFT-FRONT<br>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:16px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:140px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ABS<br>Control<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:556px;top:64px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Reference<br>Slip Rate<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:723px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Drive<br>Solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ABS<br>Control<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:293px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Drive<br>Solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ABS<br>Control<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:724px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Drive<br>Solenoid<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ABS<br>Control<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:274px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RIGHT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:351px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LEFT-FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:140px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Wheel Speed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:140px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Slip Rate<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:121px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RIGHT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:197px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LEFT-REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Slip Rate<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:293px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Slip Rate<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Slip Rate<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Wheel Speed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Wheel Speed<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:294px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Detect<br>Wheel Speed<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}