with(document) {
write("<v:group id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/SWA7EF0A20300000000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828px;top:221px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A/F SENSOR<br>(SENSOR 1)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:134px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:142px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:133px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C29<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:150px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AFS+<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:142px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:172px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C30<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:189px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AFS−<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:181px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:212px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:229px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>AFSHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:264px;top:220px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:154px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:161px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RED/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:174px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:181px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:193px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:201px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:307px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:390px;top:215px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:228px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:257px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:831px;top:455px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SECONDARY<br>HO2S<br>(SENSOR 2)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:366px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:374px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:386px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:394px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:406px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:413px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:426px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:433px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p7_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:365px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C27<br></b></nobr>");
write("</p>");
write("<p id=\"p7_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:385px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SHO2S<br></b></nobr>");
write("</p>");
write("<p id=\"p7_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:404px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:422px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SO2SHTC<br></b></nobr>");
write("</p>");
write("<p id=\"p7_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p7_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:330px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p7_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:329px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p7_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:810px;top:602px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OIL PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p7_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:564px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p7_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:582px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OPSW<br></b></nobr>");
write("</p>");
write("<p id=\"p7_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:574px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:669px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A25<br></b></nobr>");
write("</p>");
write("<p id=\"p7_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:565px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:668px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:677px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:688px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:700px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p7_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:699px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p7_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:708px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:715px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APSA<br></b></nobr>");
write("</p>");
write("<p id=\"p7_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:731px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A35<br></b></nobr>");
write("</p>");
write("<p id=\"p7_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:730px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p7_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:749px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:762px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A24<br></b></nobr>");
write("</p>");
write("<p id=\"p7_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:761px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p7_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:770px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:780px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VCC5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:793px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A18<br></b></nobr>");
write("</p>");
write("<p id=\"p7_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:792px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p7_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:801px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:808px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APSB<br></b></nobr>");
write("</p>");
write("<p id=\"p7_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:824px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A34<br></b></nobr>");
write("</p>");
write("<p id=\"p7_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:823px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:832px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:842px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>SG5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:809px;top:851px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>APP SENSOR A/B<br></b></nobr>");
write("</p>");
write("<p id=\"p7_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:881px;top:679px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p7_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:881px;top:772px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p7_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:739px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}