with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:879px;\" coordsize=\"950,879\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:879px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00D52100000000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:879px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:608px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:721px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MODULATOR UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:659px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSA MODULATOR-<br>CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:661px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Brake pressure<br>signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:661px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>· Solenoid control<br>· Motor control<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:836px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Communication via F-CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:127px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>VSA<br>OFF<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:128px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PARKING<br>BRAKE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:122px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE<br>FLUID<br>LEVEL<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHEEL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:299px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>· Engine torque control request<br>· Control mode signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:694px;top:276px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>· VSA control enable/disable<br>· Throttle open angle signal<br>· Engine revolution signal<br>· Brake pedal<br>   position switch signal<br>· Service check signal <br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733px;top:409px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Wheel rotation<br>pulse signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:242px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:121px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRAKE<br>PEDAL<br>POSITION<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:241px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:268px;top:332px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YAW RATE-LATERAL<br>ACCELERATION<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:430px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>STEERING ANGLE<br>SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:277px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>· VSA off switch signal<br>· Parking brake switch signal<br>· Brake fluid level switch signal <br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:382px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>· Yaw rate signal<br>· Lateral acceleration signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:472px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>Steering angle signal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:300px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>· Indicator drive signal<br>· Buzzer request signal<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}