with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:511px;\" coordsize=\"950,511\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:511px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SWA7E00R311000K5351YDAD75.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:511px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:13px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-FRONT FLOOR INSULATOR B (M/T model)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:98px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>243 (9.57)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:440px;top:98px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>88 (3.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:98px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>230 (9.01)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:73px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>611 (24.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:98px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>51 (2.0)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:224px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>61<br>(2.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:543px;top:229px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>64<br>(2.5)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:585px;top:307px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>24<br>(0.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:461px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>131 (5.16)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:324px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>79 (3.1)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:424px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>37.5 (1.48)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:462px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>248 (9.76)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:462px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>97 (3.8)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:448px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>100<br>(3.93)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:462px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>35 (1.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:242px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>93 (3.7)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:230px;font-weight:normal;font-size:7.6pt;\">");
write("<nobr><b>64<br>(2.5)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl3_1\" name=\"prt_bl\" class=\"drag\" from=\"715,304\" to=\"714,238\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"414 (16.3)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_2\" name=\"prt_bl\" class=\"drag\" from=\"517,315\" to=\"516,283\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(2.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_3\" name=\"prt_bl\" class=\"drag\" from=\"501,315\" to=\"500,299\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"66\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_4\" name=\"prt_bl\" class=\"drag\" from=\"411,179\" to=\"410,143\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(3.2)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_5\" name=\"prt_bl\" class=\"drag\" from=\"396,176\" to=\"395,155\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"80\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_6\" name=\"prt_bl\" class=\"drag\" from=\"340,399\" to=\"339,383\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"43\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_7\" name=\"prt_bl\" class=\"drag\" from=\"356,405\" to=\"355,376\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(1.7)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_8\" name=\"prt_bl\" class=\"drag\" from=\"234,312\" to=\"233,296\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"67\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_9\" name=\"prt_bl\" class=\"drag\" from=\"249,251\" to=\"248,209\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"188 (7.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_10\" name=\"prt_bl\" class=\"drag\" from=\"193,212\" to=\"192,178\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"29 (1.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_11\" name=\"prt_bl\" class=\"drag\" from=\"249,132\" to=\"248,98\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"26 (1.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_12\" name=\"prt_bl\" class=\"drag\" from=\"249,481\" to=\"248,446\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(1.0)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_13\" name=\"prt_bl\" class=\"drag\" from=\"234,477\" to=\"233,457\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"26\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_14\" name=\"prt_bl\" class=\"drag\" from=\"197,397\" to=\"196,363\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"29 (1.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_15\" name=\"prt_bl\" class=\"drag\" from=\"208,337\" to=\"207,261\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"511 (20.1)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_16\" name=\"prt_bl\" class=\"drag\" from=\"248,393\" to=\"247,326\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"146 (5.75)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_17\" name=\"prt_bl\" class=\"drag\" from=\"393,414\" to=\"392,354\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"114 (4.49)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_18\" name=\"prt_bl\" class=\"drag\" from=\"517,242\" to=\"516,176\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"244 (9.61)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_19\" name=\"prt_bl\" class=\"drag\" from=\"653,377\" to=\"652,348\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"104\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_20\" name=\"prt_bl\" class=\"drag\" from=\"669,381\" to=\"668,333\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(4.09)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_21\" name=\"prt_bl\" class=\"drag\" from=\"673,246\" to=\"672,172\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"243 (9.57)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_22\" name=\"prt_bl\" class=\"drag\" from=\"466,388\" to=\"465,334\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"99 (3.9)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_23\" name=\"prt_bl\" class=\"drag\" from=\"391,321\" to=\"390,289\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(2.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_24\" name=\"prt_bl\" class=\"drag\" from=\"376,315\" to=\"375,299\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"66\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_25\" name=\"prt_bl\" class=\"drag\" from=\"656,310\" to=\"655,294\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"67\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_26\" name=\"prt_bl\" class=\"drag\" from=\"711,433\" to=\"710,401\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_26\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(3.4)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_27\" name=\"prt_bl\" class=\"drag\" from=\"696,426\" to=\"695,410\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_27\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"86\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_28\" name=\"prt_bl\" class=\"drag\" from=\"775,420\" to=\"774,369\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_28\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"11 (0.43)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_29\" name=\"prt_bl\" class=\"drag\" from=\"669,319\" to=\"668,286\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_29\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(2.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl3_30\" name=\"prt_bl\" class=\"drag\" from=\"248,318\" to=\"247,273\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp3_30\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"(2.6)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:7.6pt;\"/>");
write("</v:line>");
write("</v:group>");
}