with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E20K722000R7114FAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:180px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S2 (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:156px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S4 (YEL)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:65px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S3 (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:65px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S1 (BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:140px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>R2 <br>(WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:96px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>R1 (GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:32px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MOTOR ANGLE SENSOR 8P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:270px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}