with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1132px;\" coordsize=\"950,1132\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1132px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E80A20300000000DBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1132px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:835px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>31P CONNECTOR (27)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:405px;top:638px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM/PCM A (□) (22)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:664px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>INPUT SHAFT<br>(MAINSHAFT)<br>SPEED SENSOR<br>(23) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:664px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>TRANSMISSION<br>RANGE SWITCH<br>(24) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:447px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM/PCM C (○) (20)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:638px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECM/PCM B (△) (21)*<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:291px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>SECONDARY<br>HO2S (SENSOR 2)<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:305px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>23P CONNECTOR (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:307px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ELD (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:302px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (H) (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:661px;top:303px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY<br>BOX (F) (16)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:456px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (D) (17)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:455px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>TEST<br>TACHOMETER<br>CONNECTOR<br>(18)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:431px;top:455px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>UNDER-HOOD<br>FUSE/RELAY<br>BOX (E) (19)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:37px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>MAP SENSOR<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>THROTTLE BODY<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:373px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>MAF SENSOR/<br>IAT SENSOR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:519px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>CMP SENSOR A<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:166px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>24P JUNCTION CONNECTOR (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:167px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>CMP SENSOR B<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:166px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>EGR VALVE<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:169px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ECT SENSOR 1<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:155px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>OUTPUT SHAFT<br>(COUNTERSHAFT)<br>SPEED SENSOR<br>(10) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:825px;top:154px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/F SENSOR<br>(SENSOR 1)<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:834px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>10P CONNECTOR<br>(25) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:833px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>REVERSE LOCK<br>SOLENOID VALVE<br>(26) (M/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:627px;top:839px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>3RD CLUTCH<br>TRANSMISSION<br>FLUID PRESSURE <br>SWITCH (28) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797px;top:841px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>8P CONNECTOR<br>(29) (A/T)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1px;top:1057px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br>**: Connector with female terminals (single outline): view from terminal side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}