with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:369px;\" coordsize=\"475,369\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:369px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00K732000Y1183FAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:369px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE CONNECTOR A (36P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:319px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>EPS CONTROL UNIT 20P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:338px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:35px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:192px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CANL (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:276px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CANH (WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:383px;top:122px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CANH<br>(WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:122px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CANL (RED)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}