with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:182px;\" coordsize=\"475,182\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:182px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00J34356544031FEAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:182px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:23px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:56px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:29px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:404px;top:30px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:79px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Mirrors retract<br>from extend position.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:111px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Mirrors extend<br>from retract position.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:47px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>[1]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:48px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>[3]<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}