with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:319px;\" coordsize=\"950,319\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:319px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00J22100030053BBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:319px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:44px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:25px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:94px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:75px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:145px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:125px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:195px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:175px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:135px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Gauge needles<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:185px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Beeper<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:243px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5 sec.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Self-diagnostic<br>mode<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:85px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SEL/RESET<br>switch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:214px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>The needles sweep from the<br>minimum position to the<br>maximum position, then return<br>to the minimum position.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}