with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:593px;\" coordsize=\"475,593\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:593px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00K763000Y1276FAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:593px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:523px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX CONNECTOR S (20P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:547px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:63px;top:32px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>COMBINATION LIGHT SWITCH 12P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:55px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:244px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>SMALL LT<br>SW (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:65px;top:157px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H/L OFF SW (ORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:347px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H/L OFF<br>SW <br>(ORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:156px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GND<br>(BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:348px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GND<br>(BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:478px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>SMALL LT SW (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:217px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H/L ON SW (PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:9px;top:478px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H/L ON SW (PNK)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}