with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:687px;\" coordsize=\"950,687\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:687px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E70A14680300000CAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:687px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:191px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>PRIMARY ROCKER ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:476px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:476px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:114px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY<br>ROCKER ARM B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:654px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE TIMING<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:317px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OIL<br>PRESSURE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:55px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:143px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:555px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY<br>ROCKER ARM A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:777px;top:274px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:141px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROCKER ARM<br>OIL CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:464px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EOP SENSOR<br>(KE, KG, KS models)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}