with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:863px;\" coordsize=\"950,863\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:863px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E49G24100000000DAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:863px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:792px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C PRESSURE SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:737px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RADIATOR FAN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:624px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C COMPRESSOR CLUTCH RELAY<br><a href=\"javascript:CtsProc('0','000000000002614','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:60px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FAN CONTROL RELAY<br><a href=\"javascript:CtsProc('0','000000000002614','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:30px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:523px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:399px;top:768px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A/C CONDENSER FAN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:690px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTSIDE AIR TEMPERATURE SENSOR<br><a href=\"javascript:CtsProc('0','000000000000936','i000')\"></b>Test,</a><br> in the Shop Manual, P/N 62SWA00B<br><a href=\"javascript:CtsProc('0','000000000000936','i000')\">Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:830px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is similar.<br></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:110px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUXILIARY UNDER-HOOD RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:389px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLOWER MOTOR RELAY<br><a href=\"javascript:CtsProc('0','000000000002614','i000')\"></b>Test,</a><br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}