with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/SWA7EB0A20300000000EAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:593px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 1 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:788px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 3 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:544px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:641px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C16<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:737px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C17<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:1002px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G101<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:768px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:672px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:537px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:576px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:757px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:888px;top:728px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:661px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:888px;top:632px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:564px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:888px;top:536px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:750px;top:690px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 2 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:467px;top:512px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:747px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:650px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:884px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>No. 4 IGNITION COIL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:833px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>C18<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:864px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:853px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ICM<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:888px;top:824px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>To<br>SPARK<br>PLUG<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:448px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:969px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:1057px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:932px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/<br>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:554px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:633px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:730px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:244px;top:843px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:825px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:530px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:563px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:659px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:755px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:851px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IGPLS4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:747px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:650px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:554px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:842px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:473px;top:1001px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:960px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:969px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:492px;top:512px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:512px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:512px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:544px;top:512px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:547px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:567px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:626px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:643px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:664px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:723px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:739px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:760px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:819px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:834px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:856px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:1005px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>*2: M/T<br>*3: with cruise control<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:827px;top:308px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>EVAP CANISTER<br>PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:272px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:277px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:217px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:793px;top:191px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>24P JUNCTION<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:356px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:370px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B42<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:380px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:264px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:347px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:288px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:191px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:155px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:379px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:440px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B43<br></b></nobr>");
write("</p>");
write("<p id=\"p4_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:241px;top:450px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:403px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p4_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:427px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:488px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>B41<br></b></nobr>");
write("</p>");
write("<p id=\"p4_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:497px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p4_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:183px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p4_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:209px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p4_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:280px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:371px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:395px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:420px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:296px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PCS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:388px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:458px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTF<br></b></nobr>");
write("</p>");
write("<p id=\"p4_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTC<br></b></nobr>");
write("</p>");
write("<p id=\"p4_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:288px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>YEL/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:200px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p4_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:183px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p4_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:216px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p4_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:233px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p4_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:190px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:207px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:392px;top:259px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p4_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:360px;top:259px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p4_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:333px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p4_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:241px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:208px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:265px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:190px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p4_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:143px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:844px;top:469px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:118px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>REVERSE LOCK<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p4_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:74px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p4_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:90px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p4_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:82px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p4_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:717px;top:97px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p4_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:733px;top:158px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p4_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:71px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>A27<br></b></nobr>");
write("</p>");
write("<p id=\"p4_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:89px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RVS<br></b></nobr>");
write("</p>");
write("<p id=\"p4_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:90px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p4_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:417px;top:105px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>23P<br>CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p4_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:81px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}