with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:433px;\" coordsize=\"475,433\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:433px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E30A18316217201KBAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:433px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:365px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller<br>rod<br>journal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:20px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Larger big end bore<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:106px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller bearing (Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:148px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:201px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:255px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:310px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:63px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1 or I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:64px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2 or II<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:63px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>3 or III <br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:63px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4 or IIII<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:255px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:203px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:147px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:312px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:401px;top:312px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Blue<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:365px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Smaller<br>bearing<br>(Thicker)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:20px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Big end<br>bore<br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:74px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Rod<br>journal<br>code<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:203px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:148px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:256px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:248px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown/<br>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:196px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:141px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:303px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Black/<br>Blue<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:248px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Green/<br>Brown<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:303px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Brown/<br>Black<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:196px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Yellow/<br>Green<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:141px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Pink/<br>Yellow<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}