with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:513px;\" coordsize=\"475,513\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:513px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R00000000000YCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:513px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: Spot welding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: MIG welding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:67px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: 2-Plate welding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:93px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: 3-Plate welding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:118px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: 4-Plate welding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>P = Spot welding pitch<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>L = MIG welding length<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:67px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:93px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>( ): The number of welds<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:280px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(5)<br>L = 10 (0.4)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:365px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:482px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>4-Plate welding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:179px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>(19)<br>P = 30 (1.2)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}