with(document) {
write("<v:group id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/SWA7E56J54260400000EAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:802px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU <br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:666px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:566px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ultrasonic sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:580px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Hands Free Telephone control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:666px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:652px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Alarm control siren<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:744px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:416px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Automatic lighting/rain sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:478px;top:308px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:329px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.29 (15 A)*<sup>1</sup> (20 A)*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:365px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.31 (15 A)*<sup>1</sup> (20 A)*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:293px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.28 (15 A)*<sup>1</sup> (20 A)*<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:380px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Console accessory power socket relay<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:380px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:309px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Rear accessory power socket relay<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:406px;top:308px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's seat heater<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's seat heater<br></b></nobr>");
write("</p>");
write("<p id=\"p7_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:166px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p7_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:1048px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With security)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148px;top:1001px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148px;top:951px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:1002px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn switch<br></b></nobr>");
write("</p>");
write("<p id=\"p7_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:952px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn (High)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:966px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn (Low)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:951px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:1001px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:228px;top:920px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HORN RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p7_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:848px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Without security)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:719px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With security)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:694px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:695px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Security horn<br></b></nobr>");
write("</p>");
write("<p id=\"p7_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:823px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn switch<br></b></nobr>");
write("</p>");
write("<p id=\"p7_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:823px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:801px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:715px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:495px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ignition key light<br></b></nobr>");
write("</p>");
write("<p id=\"p7_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:802px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn (Low)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:801px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:780px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p7_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:780px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Horn (High)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:667px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p7_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:201px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:73px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*2 : KE model<br></b></nobr>");
write("</p>");
write("<p id=\"p7_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:62px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>*1 :Except KE model<br></b></nobr>");
write("</p>");
write("<p id=\"p7_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:488px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p7_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:338px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p7_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:88px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p7_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:623px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Immobilizer−keyless control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p7_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:638px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AVN unit<br></b></nobr>");
write("</p>");
write("<p id=\"p7_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:609px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Data link connector (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:595px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Audio unit<br></b></nobr>");
write("</p>");
write("<p id=\"p7_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:516px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cargo area light<br></b></nobr>");
write("</p>");
write("<p id=\"p7_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:516px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:494px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:387px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:416px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:430px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Map light<br></b></nobr>");
write("</p>");
write("<p id=\"p7_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:445px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ceiling light<br></b></nobr>");
write("</p>");
write("<p id=\"p7_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:459px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's vanity mirror light <br></b></nobr>");
write("</p>");
write("<p id=\"p7_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:473px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's vanity mirror light<br></b></nobr>");
write("</p>");
write("<p id=\"p7_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:344px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:345px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front accessory  power socket relay<br></b></nobr>");
write("</p>");
write("<p id=\"p7_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:258px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.27 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:222px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.7 (Not used)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:137px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p7_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:150px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.5 (15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:537px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:40px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p7_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:566px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p7_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:186px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.6 (20 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:34px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.2 (OPTION) <br>(80 A) FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:284px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.22 (7.5 A) <br>FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:446px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.23 (10 A) FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.12 (15 A) <br>FUSE <br>(UNDER−HOOD <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:202px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left front fog light <br>(Via front fog light relay)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:230px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Right front fog light <br>(Via front fog light relay)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}