with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:994px;\" coordsize=\"475,994\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:994px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R41100000000YDAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:994px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:134px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:181px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:303px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>P, p<br>Rear Damper Mount Hole 11.5 (0.45) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:64px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>O, o<br>Front Floor Cross-member <br>Locating Hole 15 (0.59) <br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:414px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:446px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:911px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:780px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:28px;top:777px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:668px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>p<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:136px;top:729px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1688<br>(66.46)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:840px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1000<br>(39.37)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:709px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1132<br>(44.57)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:829px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1698<br>(66.85)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:725px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>2004<br>(78.90)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:782px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>1995<br>(78.54)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}