with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:972px;\" coordsize=\"950,972\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:972px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SWA7E40J54260400000EAAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:972px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Yaw rate−lateral acceleration sensor <br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA modulator−control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:233px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:261px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ELD unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:536px;top:776px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:419px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:276px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MAF sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:290px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Brake pedal position switch<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:428px;top:183px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:233px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:540px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>E−pretensioner unit (With CMBS)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:540px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:647px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Parking/back−up sensor switch<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:683px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Back−up light switch <br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:647px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:760px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.22 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:381px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.8 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:418px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p6_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:504px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p6_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:600px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:183px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Alternator<br></b></nobr>");
write("</p>");
write("<p id=\"p6_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:183px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p6_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:167px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.3 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:833px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU (IG1 WIPER)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:821px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:817px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.38 (30 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:718px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p6_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:703px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.11 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:683px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:611px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU (IG1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:560px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.10 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:576px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p6_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:576px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:474px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.9 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:504px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SRS unit<br></b></nobr>");
write("</p>");
write("<p id=\"p6_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:361px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:388px;top:326px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p6_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:134px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p6_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:36px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p6_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:310px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>No.4 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:412px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD <br>FUSE/RELAY BOX <br></b></nobr>");
write("</p>");
write("<p id=\"p6_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:447px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Adaptive front lighting control unit/ <br>headlight auto leveling control unit <br>(With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:770px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY <br>BOX (IG1 IHCC)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:227px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−HOOD <br>FUSE/RELAY BOX <br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}