with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:895px;\" coordsize=\"950,895\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:895px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40D52100000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:895px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:779px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>YAW RATE-LATERAL <br>ACCELERATION SENSOR<br><a href=\"javascript:CtsProc('0','000000000000073','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:62px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STEERING ANGLE SENSOR<br><a href=\"javascript:CtsProc('0','000000000000069','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:188px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT-REAR WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000072','iR02')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:235px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB BEARING UNIT<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000000017','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:536px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-REAR WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000072','iR02')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:582px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB BEARING UNIT<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000000017','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:644px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT-FRONT WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000072','iR01')\"></b>Replacement,</a><br> in the Shop Manual,<br> P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL BEARING<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000003873','i000')\"></b>Replacement,</a><br> in the Shop Manual,<br> P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:692px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-FRONT WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000072','iR01')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:740px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL BEARING<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000003873','i000')\"></b>Replacement,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:124px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA OFF SWITCH<br><a href=\"javascript:CtsProc('0','000000000000071','i000')\"></b>Test,</a><br> in the Shop Manual, P/N 62SWA00B<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:306px;top:93px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:173px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TSA RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:581px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:660px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VSA MODULATOR-CONTROL UNIT<br><a href=\"javascript:CtsProc('0','000000000002352','i000')\"></b>Removal and Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:868px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is symmetrical.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}