with(document) {
write("<v:group id=\"group3\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect3\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img3\" name=\"PrtImgId\" src=\"../img/SWA7E40000000000000EBA303.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p3_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-94px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p3_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:398px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:278px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT FRONT POSITION LIGHT (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:269px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT FRONT POSITION LIGHT (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:304px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LICENSE PLATE LIGHTS (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:296px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT TAILLIGHT (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:287px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT TAILLIGHT (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:273px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:599px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ECM (4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:477px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRAKE LIGHTS (9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:486px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:495px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ACC UNIT (16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:451px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ACC UNIT (16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:442px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-158px;top:264px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-158px;top:273px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(21−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-111px;top:256px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(20−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-111px;top:247px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(19−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-124px;top:380px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-124px;top:389px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-144px;top:362px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-144px;top:371px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-146px;top:344px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-146px;top:353px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:144px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*10 : With navigation<br></b></nobr>");
write("</p>");
write("<p id=\"p3_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:442px;top:320px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(KS model)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:398px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:367px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>60<br></b></nobr>");
write("</p>");
write("<p id=\"p3_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:137px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*9 : Without audio system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:130px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*8 : With audio system<br></b></nobr>");
write("</p>");
write("<p id=\"p3_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:108px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*5 : LHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p3_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:116px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*6 : KS model<br></b></nobr>");
write("</p>");
write("<p id=\"p3_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:123px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*7 : RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p3_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:300px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DAYTIME RUNNING LIGHT RELAY (3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:211px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CMBS OFF SWITCH LIGHT (16−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:229px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HVAC CONTROL UNIT LIGHT (18−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:238px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>NAVIGATION UNIT (19−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:149px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AMBIENT LIGHT (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-113px;top:336px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-113px;top:327px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-109px;top:309px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-109px;top:318px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:176px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PASSENGER'S SEAT HEATER SWITCH LIGHT (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-90px;top:510px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-156px;top:532px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(Without ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-196px;top:553px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRAKE LIGHTS (9−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:615px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>52<br></b></nobr>");
write("</p>");
write("<p id=\"p3_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:389px;top:586px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:291px;top:624px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>109<br></b></nobr>");
write("</p>");
write("<p id=\"p3_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:615px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>108<br></b></nobr>");
write("</p>");
write("<p id=\"p3_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:586px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:624px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p3_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:31px;top:346px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:19px;top:367px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:577px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>STARTER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:488px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SOLENOID<br></b></nobr>");
write("</p>");
write("<p id=\"p3_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:11px;top:488px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p3_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:426px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p3_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:12px;top:426px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:646px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT/BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:646px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT/GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:661px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p3_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:661px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:661px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:695px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VOLTAGE REGULATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:838px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RECTIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p3_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:646px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p3_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:646px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p3_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:661px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p3_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:679px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>IG<br></b></nobr>");
write("</p>");
write("<p id=\"p3_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:679px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p3_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:679px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p3_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:3px;top:856px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p3_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:304px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:287px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:296px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:278px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:269px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p3_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:238px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (5−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:212px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>97<br></b></nobr>");
write("</p>");
write("<p id=\"p3_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:183px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:183px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:212px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>66<br></b></nobr>");
write("</p>");
write("<p id=\"p3_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:212px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p3_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:183px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p3_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:273px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:238px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:238px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>106<br></b></nobr>");
write("</p>");
write("<p id=\"p3_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:274px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>107<br></b></nobr>");
write("</p>");
write("<p id=\"p3_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:282px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p3_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:264px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p3_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:238px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p3_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:80px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:87px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p3_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:101px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4 : Without HID<br></b></nobr>");
write("</p>");
write("<p id=\"p3_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:94px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3 : With HID<br></b></nobr>");
write("</p>");
write("<p id=\"p3_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:327px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT FRONT POSITION LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:185px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>POWER MIRROR SWITCH LIGHT (14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:114px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HEADLIGHT LEVELING SWITCH LIGHT (8−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:380px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LICENSE PLATE LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p3_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:194px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SUNSHADE SWITCH LIGHT (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:131px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HAZARD WARNING SWITCH LIGHT (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:220px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CLIMATE CONTROL UNIT LIGHT (17−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:140px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GLOVE BOX LIGHT (10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:309px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT FRONT POSITION LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:167px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER SWITCH LIGHT (12−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:247px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUDIO REMOTE SWITCH LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p3_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:158px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PARKING/BACK−UP SENSOR SWITCH LIGHT (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:203px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA OFF SWITCH LIGHT (15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-189px;top:123px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AFS  OFF/CMBS OFF SWITCH LIGHT (9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:36px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p3_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-194px;top:730px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT POWER MIRROR DEFOGGER <br>(14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-577px;top:679px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER <br>RELAY <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-194px;top:748px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT POWER MIRROR DEFOGGER <br>(14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-194px;top:828px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT FRONT FOG LIGHT <br>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-194px;top:810px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT FRONT FOG LIGHT <br>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:215px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DAYTIME RUNNING <br>LIGHT RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p3_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:186px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.36 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:186px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.7 (10 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:7px;top:186px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.15 (7.5 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:5px;top:348px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BATTERY <br>(1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:588px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No. 1 (100 A) <br>FUSE <br>(1−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:588px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No. 3 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p3_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:334px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ST <br>(IGNITION <br>SWITCH) <br>(2−C)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}