with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1087px;\" coordsize=\"950,1087\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1087px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E30A20326428001MAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1087px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:45px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BASE GASKET<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:228px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:256px;top:55px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:170px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:84px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:269px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL TANK UNIT LOCKNUT<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:146px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOCKNUT PLATE<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:442px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To FUEL RAIL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:556px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To EVAPORATIVE<br>EMISSION (EVAP)<br>CANISTER PURGE VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:929px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TOP SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:929px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TOP SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:958px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>135 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:1011px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>135 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:1035px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>positioned as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:1035px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>positioned as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:898px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>C:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:307px;top:898px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>D:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:654px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>When installing the fuel fill<br>neck tube, align the mark on the<br>tube with the projection on the<br>fill neck fitting.<br></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:777px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>120 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:809px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>30 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:820px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TOP SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:852px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>There should be<br>no clearance.<br></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:612px;top:656px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Mark<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:727px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>45 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:690px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>90 °<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:858px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure the clamp is<br>positioned as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:905px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>There should be<br>no clearance.<br></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:854px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Make sure <br>the clamp is<br>positioned <br>as shown.<br></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:762px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TOP SIDE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>A:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>B:<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}