with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:1900px; height:950px;\" coordsize=\"1900,950\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:1900px;height:950px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E50000000000000EBAD15.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:1900px;height:950px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:721px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1165px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1608px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1470px;top:210px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1470px;top:202px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:123px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*5 : K24Z1 engine<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:130px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*6 : R20A1 and R20A2 engines<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1091px;top:806px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1089px;top:814px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G503]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:542px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:139px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[    ] : RHD type<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1201px;top:464px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1219px;top:193px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1197px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1178px;top:674px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>186<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1178px;top:492px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1289px;top:488px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>149<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1091px;top:369px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:518px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1061px;top:420px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:894px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1205px;top:280px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1193px;top:265px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:917px;top:376px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HALL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:280px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SUNSHADE CONTROL UNIT/MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1231px;top:413px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1286px;top:465px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1138px;top:607px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(CLOSE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1041px;top:607px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(OPEN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1138px;top:600px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1041px;top:600px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUTO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1058px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1047px;top:518px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1058px;top:538px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1063px;top:564px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>OPEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1116px;top:564px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CLOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1116px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1089px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1074px;top:518px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1176px;top:518px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1187px;top:538px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1116px;top:538px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1089px;top:538px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1105px;top:518px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1187px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1176px;top:651px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1196px;top:581px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1196px;top:588px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(0.84 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1092px;top:651px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1103px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1092px;top:687px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1637px;top:169px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1644px;top:168px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: Without mirror turn and with retractable mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1644px;top:159px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: Without mirror turn and with mirror defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:116px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4 : With retractable mirror<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:751px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:751px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:760px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:760px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:760px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:760px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:751px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:751px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:413px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:307px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:527px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>186<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1462px;top:758px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>186<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1568px;top:814px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G503]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:193px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:488px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:109px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3 : With power mirror defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:95px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*1 : UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1635px;top:102px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*2 : UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1637px;top:151px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1644px;top:150px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>: With mirror turn, retractable mirror and mirror defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1679px;top:633px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>TILT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1732px;top:294px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1722px;top:265px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1571px;top:762px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1581px;top:688px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1571px;top:704px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1774px;top:465px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1763px;top:427px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1537px;top:480px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1526px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1537px;top:591px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1537px;top:617px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>OPEN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1595px;top:617px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CLOSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1391px;top:389px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HALL SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1471px;top:294px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1460px;top:265px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1668px;top:265px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1679px;top:294px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1373px;top:480px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1675px;top:480px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1595px;top:480px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1568px;top:480px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1553px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1557px;top:434px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1649px;top:688px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SUNROOF SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1569px;top:806px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1363px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1460px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1471px;top:591px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1675px;top:591px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1595px;top:591px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1568px;top:591px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1659px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1584px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1471px;top:688px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1460px;top:704px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1570px;top:382px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:476px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:363px;top:434px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>EXTEND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:250px;top:434px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RETRACT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:491px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:350px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:733px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RETRACT ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:806px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:157px;top:771px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:771px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:687px;top:806px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:750px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT POWER MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:733px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RETRACT ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:733px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MIRROR ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:449px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:449px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:449px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:449px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:307px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:332px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:619px;top:316px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:409px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:294px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:265px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:775px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:610px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:736px;top:806px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:616px;top:713px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:614px;top:669px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:713px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:540px;top:669px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:669px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:669px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:713px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:233px;top:713px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:338px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:285px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:600px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:396px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:562px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:750px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LEFT POWER MIRROR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:733px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MIRROR ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:294px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:294px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>POWER MIRROR SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:462px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:265px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:589px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611px;top:579px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:617px;top:588px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>: 6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:265px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>113<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:222px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1462px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>125<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1672px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>79<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1725px;top:221px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1462px;top:523px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:193px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1692px;top:193px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1743px;top:193px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1485px;top:495px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1777px;top:523px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>150<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1637px;top:160px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:174px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:21px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Power Mirrors, Sunshade, Sunroof<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1838px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:35px;font-weight:normal;font-size:17.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1772px;top:542px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1613px;top:653px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUTO <br>(CLOSE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1452px;top:497px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1688px;top:351px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CLOSE <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1555px;top:351px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>OPEN <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1480px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LIGHT <br>(0.84 W)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1520px;top:653px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUTO <br>(OPEN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1712px;top:195px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.1 (7.5 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1659px;top:195px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.24 (20 A) <br>FUSE <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1453px;top:195px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ECM/PCM <br>(4−D) <br>(5−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1351px;top:287px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SUNROOF <br>CONTROL UNIT/MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:464px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUTO TURN <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:362px;top:635px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AUTO TURN <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:194px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:644px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>POWER <br>MIRROR <br>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:188px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>POWER MIRROR <br>DEFOGGER <br>RELAY <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:644px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>POWER <br>MIRROR <br>DEFOGGER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:476px;top:194px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.36 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1448px;top:777px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(Built int the <br>gauge control <br>module) <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1112px;top:339px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CLOSE <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1076px;top:339px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>OPEN <br>RELAY <br>CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1284px;top:507px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1236px;top:583px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>SUNSHADE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1186px;top:195px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.24 (20 A) <br>FUSE <br>(3−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1167px;top:466px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.14 (7.5 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:1165px;top:693px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(Built int the <br>gauge control <br>module) <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:752px;top:546px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br>(Built int the <br>gauge control <br>module) <br>(7−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:814px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G502]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:814px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>[G501]<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}