with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1055px;\" coordsize=\"950,1055\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1055px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E50E16226600000LDAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1055px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:23px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SET RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:54px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INBOARD JOINT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:68px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:525px;top:169px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPIDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOUBLE LOOP BANDS<br>(Boot band replacement only)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:242px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INBOARD BOOT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:295px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Use the grease included<br>in the inboard boot set.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:356px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Use the grease included<br>in the inboard boot set.<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:405px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOW PROFILE BANDS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:576px;top:497px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVESHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:758px;top:543px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>STOP RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:916px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTBOARD BOOT (TPE)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:650px;top:814px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTBOARD JOINT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:462px;top:713px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EAR CLAMP BANDS<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:1010px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Use the grease included<br>in the outboard boot set.<br></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:311px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Right driveshaft<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:393px;top:110px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CIRCLIP<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}