with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\" coordsize=\"950,831\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:831px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E1PE10411200000CAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:237px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:40px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAINSHAFT <br>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:480px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT <br>1ST GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:445px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY SHAFT <br>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:715px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER (4WD)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:276px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IDLER SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:372px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IDLER SHAFT<br>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:350px;top:515px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY SHAFT<br>1ST GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:705px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FINAL DRIVEN GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:746px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:149px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:196px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FINAL DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:337px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:548px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER<br>DRIVE GEAR<br>(HYPOID GEAR)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:760px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER<br>OUTPUT SHAFT<br>(HYPOID GEAR)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:351px;top:477px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1ST CLUTCH<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}