with(document) {
write("<v:group id=\"group16\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:879px;\" coordsize=\"950,879\">");
write("<v:rect id=\"rect16\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:879px;\">");
write("<img id=\"img16\" name=\"PrtImgId\" src=\"../img/SWA7E70A20300000000DBAD16.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:879px;border-color:#ffffff\">");
write("<p id=\"p16_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:842px;top:479px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p16_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:50px;top:707px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE<br>COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p16_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:627px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE WIRE<br>HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p16_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:194px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p16_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:101px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p16_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:62px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p16_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:41px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p16_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:377px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p16_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p16_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:34px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p16_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:683px;top:44px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p16_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:61px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p16_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:105px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p16_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:545px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p16_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:726px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p16_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587px;top:838px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p16_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:805px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p16_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:698px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p16_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:605px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p16_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:506px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p16_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:780px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE OIL<br>LEVEL SENSOR<br>SUBHARNESS<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}