with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:671px;\" coordsize=\"950,671\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:671px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E80A14680800000CAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:671px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:372px;top:182px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTC<br>RETARD<br>CHAMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>From No. 3<br>ALTERNATOR<br>(10 A) FUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:90px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VARIOUS<br>SENSORS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:109px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/<br>PCM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:86px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CMP SENSOR A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTAKE<br>CAMSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:110px;top:183px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTC<br>ADVANCE<br>CHAMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:319px;top:114px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ADVANCE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:114px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RETARD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:156px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VANE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:280px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTC ACTUATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:328px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VANE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:370px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:250px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>DRAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:306px;font-weight:normal;font-size:5.7pt;\">");
write("<nobr><b>DRAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:630px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>From<br>OIL PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:346px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTC OIL CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:613px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SPOOL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:599px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROCKER ARM<br>OIL CONTROL<br>VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:449px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ROCKER<br>ARM OIL<br>PRESSURE<br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:271px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:489px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:147px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:176px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:61px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:529px;top:89px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:17px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:606px;top:434px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:362px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:51px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRN/YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:493px;top:593px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VTC STRAINER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}