with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:224px;\" coordsize=\"475,224\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:224px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00J34356544031FEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:224px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:56px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Position<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:189px;top:24px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Terminal<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:32px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:87px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>TILT UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:119px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>TILT DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:151px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>SWING LEFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:183px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>SWING RIGHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:420px;top:32px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:32px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:50px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>[4]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:50px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>[5]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:50px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>[6]<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}