with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:319px;\" coordsize=\"950,319\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:319px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E1PE10474000000CAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:319px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:19px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Power flow<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:57px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>The power flows by way of:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:88px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Engine<br>  ↓<br>Drive plate<br>  ↓<br>Torque converter cover<br>  ↓<br>Torque converter clutch piston<br>  ↓<br>Damper spring<br>  ↓<br>Turbine<br>  ↓<br>Mainshaft<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:130px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>To ATF cooler<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:153px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INLET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:153px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTLET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:43px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER SPRING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:660px;top:78px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TURBINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:631px;top:289px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE CONVERTER<br>CLUTCH PISTON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:132px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE <br>CONVERTER<br>COVER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}