with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:799px;\" coordsize=\"950,799\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:799px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00D10600000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:799px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:93px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT-REAR WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000039','iR02')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:715px;top:125px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB BEARING UNIT<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000000017','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:459px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-REAR WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000039','iR02')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:491px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HUB BEARING UNIT<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000000017','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:568px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT-FRONT WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000039','iR01')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:601px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL BEARING<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000003873','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:615px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT-FRONT WHEEL SENSOR<br><a href=\"javascript:CtsProc('0','000000000000039','iR01')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:647px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL BEARING<br>(MAGNETIC ENCODER)<br><a href=\"javascript:CtsProc('0','000000000003873','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:493px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ABS MODULATOR-<br>CONTROL UNIT<br></b>Removal and<br><a href=\"javascript:CtsProc('0','000000000000038','i000')\"> Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:567px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:15px;top:753px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD type is shown, RHD type is symmetrical.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:318px;top:708px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:411px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}