with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:497px;\" coordsize=\"475,497\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:497px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00J26273400000KDAD31.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:497px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Fastener Locations<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: Clip, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:38px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: Clip, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:155px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>: Clip, 2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:41px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:126px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:364px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:300px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:145px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:127px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:289px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:274px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:252px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:457px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:252px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:270px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:107px;top:277px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}