with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1071px;\" coordsize=\"950,1071\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1071px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R51100000000YDAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1071px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME UPPER <br>STIFFENER REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:117px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:609px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:241px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:493px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:422px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:864px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:234px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:163px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME UPPER <br>STIFFENER REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:38px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR <br>WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:510px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:149px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:206px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:771px;top:363px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:38px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br>UPPER STIFFENER<br>REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:102px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794px;top:89px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL<br>UPPER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:848px;top:323px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TIE DOWN<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:881px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME UPPER <br>STIFFENER REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:566px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br>UPPER STIFFENER<br>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:628px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR DAMPER<br>BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME <br>UPPER STIFFENER <br>FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:293px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME UPPER <br>STIFFENER FRONT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:208px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME UPPER <br>STIFFENER REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:410px;top:59px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>120 mm<br>(4.72 in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:1008px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br>UPPER STIFFENER <br>REAR PATCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:772px;top:1008px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL  <br>SIDE STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:972px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR PANEL  <br>SIDE STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:678px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Except KE, KG, KS, KH, KQ,<br>and KZ models<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:678px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KE, KG, KS, KH, KQ,<br>and KZ models<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:821px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[Area: A]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:279px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[A]<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}