with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R51100000000YDAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:176px;top:84px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:98px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:220px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>LOWER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:320px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JOINT COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:327px;top:639px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE FRAME<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:649px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BACKPLATE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:22px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:35px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>UPPER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:120px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER<br>EXTENSION A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:189px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER<br>HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:768px;top:509px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:740px;top:637px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:526px;top:592px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSMISSION<br>MOUNT BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:573px;top:702px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT<br>WHEELHOUSE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:131px;top:715px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Right Side<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:1056px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT<br>WHEELHOUSE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:896px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE ROD<br>BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:671px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:945px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:1041px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER HOUSING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:352px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER<br>EXTENSION B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:748px;top:232px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER<br>EXTENSION A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:153px;top:519px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT<br>WHEELHOUSE <br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:96px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER<br>BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:696px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD SIDE<br>MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:83px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER<br>EXTENSION A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}