with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E00D10600000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:33px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-HOOD FUSE/RELAY BOX<br>CONNECTOR C (2P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:374px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE PEDAL POSITION<br>SWITCH 4P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:24px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BRAKE FLUID LEVEL SWITCH<br>2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:844px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK CONNECTOR (DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:98px;top:799px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ECM/PCM CONNECTOR A (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:734px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:373px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE CONNECTOR B (36P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:522px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ABS MODULATOR-CONTROL UNIT 26P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:551px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL SENSOR<br>2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:185px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX CONNECTOR F (34P)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:1044px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}