with(document) {
write("<v:group id=\"group4\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect4\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img4\" name=\"PrtImgId\" src=\"../img/SWA7E54J54230100000EAAD04.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p4_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:753px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left power mirror defogger<br></b></nobr>");
write("</p>");
write("<p id=\"p4_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p4_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:1019px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p4_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:1016px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:1018px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Panorama roof subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:1039px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Roof wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:1038px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:1039px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p4_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:1038px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:1039px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:1039px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:918px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p4_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:903px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:903px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:903px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Gauge control module<br></b></nobr>");
write("</p>");
write("<p id=\"p4_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:639px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunshade control unit/motor<br></b></nobr>");
write("</p>");
write("<p id=\"p4_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:640px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p4_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:639px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:618px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunshade switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:603px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof control unit/motor<br></b></nobr>");
write("</p>");
write("<p id=\"p4_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:561px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Front passenger's vanity mirror light<br></b></nobr>");
write("</p>");
write("<p id=\"p4_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:575px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Automatic lighting/rain sensor<br></b></nobr>");
write("</p>");
write("<p id=\"p4_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:589px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Sunroof switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p4_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:341px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p4_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A/C subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:995px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p4_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:1018px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p4_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:558px;top:1039px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's switch subharness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:1038px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:1040px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p4_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:882px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Ignition key switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:868px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Cable reel<br></b></nobr>");
write("</p>");
write("<p id=\"p4_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:832px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CMBS OFF switch (With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:846px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight leveling switch (Without HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:818px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AFS OFF switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:689px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left side turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p4_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's vanity mirror light<br></b></nobr>");
write("</p>");
write("<p id=\"p4_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:953px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p4_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power window master switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:803px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:739px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Left side turn signal light<br></b></nobr>");
write("</p>");
write("<p id=\"p4_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:803px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power mirror switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:803px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA OFF switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:456px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door lock knob switch/key cylinder switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:725px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power window master switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:868px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:546px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:775px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:803px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:868px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:675px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p4_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:484px;top:711px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p4_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:804px;font-weight:normal;font-size:5.6pt;\">");
write("<nobr><b>AB<br></b></nobr>");
write("</p>");
write("<p id=\"p4_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:403px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Millimeter wave radar unit (With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:368px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p4_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Headlight washer control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p4_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:1018px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p4_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p4_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p4_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:554px;top:132px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p4_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:475px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:332px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:303px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:267px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p4_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power transister<br></b></nobr>");
write("</p>");
write("<p id=\"p4_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:210px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:282px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Power steering pressure (PSP) switch (Without EPS)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:525px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G402<br></b></nobr>");
write("</p>");
write("<p id=\"p4_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:475px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:475px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>EPS control unit <br></b></nobr>");
write("</p>");
write("<p id=\"p4_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:103px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:89px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p4_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:63px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(Fuse/relay box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:268px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Brake fluid level switch<br></b></nobr>");
write("</p>");
write("<p id=\"p4_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:132px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G602<br></b></nobr>");
write("</p>");
write("<p id=\"p4_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:332px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:303px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:268px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:67px;top:453px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p4_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:175px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:75px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:132px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p4_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:1018px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Dashboard wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Side wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:995px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:1016px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:995px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:996px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Engine compartment wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:94px;top:1016px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p4_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:1018px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Driver's door wire harness<br></b></nobr>");
write("</p>");
write("<p id=\"p4_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:32px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p4_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:239px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Clutch pedal position switch <br>(M/T with cruise control)<br></b></nobr>");
write("</p>");
write("<p id=\"p4_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:332px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Adaptive cruise control <br>(ACC) control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p4_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:367px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Adaptive cruise control <br>(ACC) control unit<br></b></nobr>");
write("</p>");
write("<p id=\"p4_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:303px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Adaptive front lighting control unit/ <br>headlight auto leveling control unit (With HID)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}