with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E50J201000K0121LEAD91.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:200px;top:495px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a1<br>M14 x 1.5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:517px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c2<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:385px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:348px;top:517px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a3<br>M14 x 1.5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:490px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a4<br>M14 x 1.5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:188px;top:396px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>b1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:192px;top:321px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>b2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:333px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>b3<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:361px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c1<br>M10 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:337px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c3<br>M10 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:298px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c4<br>M10 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:285px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>d1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:248px;top:302px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>d2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:324px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:336px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:327px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:346px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:318px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:295px;top:409px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:399px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>f<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:426px;top:405px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>g<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:396px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>h<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:474px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>i1, i2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:388px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>j1, j2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:469px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>k<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:355px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>l1<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:327px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>l2<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:349px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:470px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>m1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:455px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>m2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:657px;top:512px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>n<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:330px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>p2<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:335px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>p1<br>M12 x 1.25<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:354px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>q<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:361px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>r<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:237px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>[ SECTION :AA ]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:276px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>[ SECTION: BB ]<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:805px;top:167px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>3−11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:334px;top:86px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>15 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:386px;top:92px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>120 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:151px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>120 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:370px;top:167px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>6 °<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:398px;top:136px;font-weight:normal;font-size:3.6pt;\">");
write("<nobr><b>3−11.5 (0.45)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:375px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:423px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:44px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>h<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:57px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>i1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:70px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>i2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:83px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>j1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:95px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>j2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:108px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>k<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:121px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>l1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:134px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>l2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:147px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>m1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:160px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>m2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:173px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>n<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:186px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>o<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:199px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>p1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:211px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>p2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:224px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>q<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:237px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>r<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:44px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Front floor locating hole φ25 (0.98) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:57px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Middle floor cross-member locating hole φ15 (0.59) right side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:70px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Middle floor cross-member locating hole φ15 (0.59) left side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:83px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear floor locating hole φ25 (0.98) right side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:95px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear floor locating hole φ25 (0.98) left side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:108px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear frame A locating hole φ20 (0.79)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:121px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For trailing arm mount φ17 (0.67) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:134px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For trailing arm mount φ17 (0.67) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:147px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear floor cross-member locating hole φ15 (0.59) right side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:160px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear floor cross-member locating hole φ15 (0.59) left side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:173px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For cross beam mount φ15 (0.59)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:186px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear damper center 68 (2.7) x 73 (2.9) slot<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:199px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For cross beam mount φ15 (0.59) right side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:211px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For cross beam mount φ15 (0.59) left side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:224px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear floor locating hole φ50 (1.97)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:515px;top:237px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Rear frame B locating hole φ25 (0.98)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:44px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:57px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:70px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:83px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>a4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:95px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>b1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:108px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>b2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:121px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>b3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:134px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:147px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:160px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:173px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>c4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:186px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>d1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:199px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>d2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:211px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:224px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:237px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:250px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>e4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:263px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>f<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:276px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>g<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:44px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:57px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For front subframe mount φ13 (0.51) middle<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:70px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:83px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For front subframe mount φ16 (0.63) center side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:95px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For engine side mount φ17 (0.67) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:108px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For engine side mount φ17 (0.67) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:121px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For engine side mount φ13 (0.51) wheelhouse side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:134px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For transmission mount φ 13 (0.51) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:147px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51) middle<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:160px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For transmission mount φ13 (0.51) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:173px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For transmission mount φ11 (0.43) wheelhouse side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:186px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For torque rod upper mount 14.5 (0.57) x 19.5 (0.78) slot<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:199px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For torque rod lower mount 13 (0.51) x 21 (0.83) slot<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:211px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For damper mount φ11.5 (0.45) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:224px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Front damper center hole φ74 (2.9)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:237px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For damper mount φ11.5 (0.45) center side<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:250px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>For damper mount φ11.5 (0.45) rearward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:263px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Outrigger locating hole φ27.4 (1.08)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:276px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Front floor locating hole φ50 (1.97) forward<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:13px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:22px;top:26px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>φ: Inner diameter<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:539px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>VERTICAL LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:438px;font-weight:normal;font-size:4.5pt;\">");
write("<nobr><b>BASE<br>LINE<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("<v:line id=\"bl2_1\" name=\"prt_bl\" class=\"drag\" from=\"553,417\" to=\"552,375\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_1\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"193 (7.60)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_2\" name=\"prt_bl\" class=\"drag\" from=\"92,424\" to=\"91,347\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_2\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"603 (23.7) e1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_3\" name=\"prt_bl\" class=\"drag\" from=\"103,427\" to=\"102,356\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_3\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"595 (23.4) e2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_4\" name=\"prt_bl\" class=\"drag\" from=\"113,434\" to=\"112,376\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_4\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"470 (18.5) d1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_5\" name=\"prt_bl\" class=\"drag\" from=\"124,437\" to=\"123,387\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_5\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"407 (16.0) d2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_6\" name=\"prt_bl\" class=\"drag\" from=\"135,437\" to=\"134,384\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_6\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"371 (14.6) c4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_7\" name=\"prt_bl\" class=\"drag\" from=\"145,438\" to=\"144,386\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_7\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"363 (14.3) b3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_8\" name=\"prt_bl\" class=\"drag\" from=\"157,495\" to=\"156,437\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_8\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"234 (9.21) b2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_9\" name=\"prt_bl\" class=\"drag\" from=\"167,495\" to=\"166,441\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_9\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"233 (9.17) c1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_10\" name=\"prt_bl\" class=\"drag\" from=\"177,495\" to=\"176,440\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_10\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"217 (8.54) b1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_11\" name=\"prt_bl\" class=\"drag\" from=\"198,488\" to=\"197,445\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_11\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"72 (2.83)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_12\" name=\"prt_bl\" class=\"drag\" from=\"239,478\" to=\"238,434\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_12\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"171 (6.23)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_13\" name=\"prt_bl\" class=\"drag\" from=\"267,478\" to=\"266,432\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_13\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"237 (9.33)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_14\" name=\"prt_bl\" class=\"drag\" from=\"284,490\" to=\"283,439\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_14\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"18 (0.71) a2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_15\" name=\"prt_bl\" class=\"drag\" from=\"311,505\" to=\"310,460\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_15\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"94 (3.70) a4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_16\" name=\"prt_bl\" class=\"drag\" from=\"321,505\" to=\"320,456\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_16\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"92 (3.62) a3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_17\" name=\"prt_bl\" class=\"drag\" from=\"331,504\" to=\"330,458\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_17\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"77 (3.03) f\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_18\" name=\"prt_bl\" class=\"drag\" from=\"377,422\" to=\"376,376\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_18\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"590 (23.2) e3\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_19\" name=\"prt_bl\" class=\"drag\" from=\"389,419\" to=\"388,362\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_19\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"592 (23.3) e4\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_20\" name=\"prt_bl\" class=\"drag\" from=\"399,487\" to=\"398,452\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_20\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"10 (0.39)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_21\" name=\"prt_bl\" class=\"drag\" from=\"526,491\" to=\"525,448\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_21\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"34 (1.34)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_22\" name=\"prt_bl\" class=\"drag\" from=\"569,483\" to=\"568,447\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_22\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"6 (0.24)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_23\" name=\"prt_bl\" class=\"drag\" from=\"594,481\" to=\"593,446\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_23\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"2 (0.08)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_24\" name=\"prt_bl\" class=\"drag\" from=\"618,482\" to=\"617,445\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_24\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"3 (0.12)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_25\" name=\"prt_bl\" class=\"drag\" from=\"632,483\" to=\"631,447\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_25\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"4 (0.16)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_26\" name=\"prt_bl\" class=\"drag\" from=\"680,504\" to=\"679,428\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_26\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"94 (3.70) m1, m2, n\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_27\" name=\"prt_bl\" class=\"drag\" from=\"694,495\" to=\"693,437\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_27\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"212 (8.35) o\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_28\" name=\"prt_bl\" class=\"drag\" from=\"713,492\" to=\"712,436\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_28\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"115 (4.53) p2\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_29\" name=\"prt_bl\" class=\"drag\" from=\"724,493\" to=\"723,438\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_29\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"139 (5.47) p1\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_30\" name=\"prt_bl\" class=\"drag\" from=\"739,479\" to=\"738,441\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_30\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"10 (0.39)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("<v:line id=\"bl2_31\" name=\"prt_bl\" class=\"drag\" from=\"771,485\" to=\"770,430\" strokecolor=\"black\">");
write("<v:fill class=\"drag\" on=\"true\" color=\"black\"/>");
write("<v:path class=\"drag\" textpathok=\"true\"/>");
write("<v:textpath id=\"tp2_31\" name=\"PrtTpId\" class=\"drag\" on=\"true\" string=\"139 (5.47)\" style=\"font-family:Arial;text-align:left;font-weight:small;font-size:3.6pt;\"/>");
write("</v:line>");
write("</v:group>");
}