with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40J10300000000EAAD92.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:14px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:89px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:785px;top:89px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:830px;top:46px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[     ]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:46px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:46px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:37px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>With tweeter<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:37px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:37px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:23px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>With subwoofer<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:23px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:23px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:30px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:30px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:843px;top:30px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>Without subwoofer<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:59px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:863px;top:55px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>: Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:43px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:76px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:63px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:84px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:89px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SUBWOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590px;top:116px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:111px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:116px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:116px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:111px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:111px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:116px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:111px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:116px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:523px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:546px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:512px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:557px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590px;top:177px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:532px;top:172px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:571px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:551px;top:172px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:379px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(1 DIN type)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:601px;top:357px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUXILIARY JACK ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:333px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:346px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:672px;top:346px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:621px;top:346px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:620px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:595px;top:346px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:569px;top:346px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:594px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:670px;top:252px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:577px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:603px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:596px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:629px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:655px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:426px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[BLU]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:366px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[RED]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:366px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[YEL]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:366px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:366px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[BLK]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:695px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:496px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(Except 1 DIN type)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:463px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:459px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:463px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:459px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:780px;top:459px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:463px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:463px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:459px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:459px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:806px;top:463px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:426px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:832px;top:426px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:420px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:332px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:306px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[GRN]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:755px;top:306px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[WHT]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:450px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:450px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:450px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:450px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:450px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:475px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUXILIARY JACK ASSEMBLY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856px;top:252px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:856px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:280px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:833px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SGND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:808px;top:360px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:840px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:834px;top:360px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:782px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:360px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:789px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:360px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:360px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:861px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:841px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:841px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:798px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:818px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:712px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:689px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:666px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:646px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:754px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:866px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:846px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:803px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:817px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:738px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:718px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:860px;top:146px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:243px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT <br>TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:796px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LEFT REAR <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:759px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT <br>TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT REAR <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:100px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:26px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 14 (15 A) FUSE <br>(In the under−hood <br>fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:49px;top:70px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>D19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:114px;top:177px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:50px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:52px;top:46px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:129px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:191px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:190px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:198px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>:<br></b></nobr>");
write("</p>");
write("<p id=\"p1_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:198px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:202px;top:198px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:503px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G504<br></b></nobr>");
write("</p>");
write("<p id=\"p1_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:440px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:310px;top:353px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUDIO REMOTE SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:300px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:329px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REMOTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:365px;top:252px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:252px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUDIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:257px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>REMOTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:440px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:286px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_250\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_251\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:221px;top:343px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_252\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:178px;top:343px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_253\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:399px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_254\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:235px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_255\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:258px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_256\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:380px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3.9kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_257\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:343px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_258\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_259\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:286px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_260\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:321px;top:400px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MODE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_261\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_262\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:400px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_263\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:396px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_264\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:396px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VOL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_265\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:400px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DOWN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_266\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:405px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(<br></b></nobr>");
write("</p>");
write("<p id=\"p1_267\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:399px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_268\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>100Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_269\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:380px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>270Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_270\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:380px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>470Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_271\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:380px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1.2kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_272\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:380px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_273\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:286px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_274\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:270px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_275\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:261px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ILL−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_276\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:403px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(+)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_277\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:275px;top:403px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(−)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_278\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:358px;top:487px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(With audio remote switch)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_279\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:353px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_280\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:161px;top:343px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_281\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:353px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_282\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:353px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_283\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:361px;top:410px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_284\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:184px;top:430px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_285\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:430px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_286\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:440px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_287\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:195px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_288\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:213px;top:207px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SUBWOOFER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_289\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:177px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_290\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:152px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_291\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:126px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AMPLIFIER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_292\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:70px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ANTENNA MAST<br></b></nobr>");
write("</p>");
write("<p id=\"p1_293\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:67px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_294\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:27px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_295\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:53px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>E14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_296\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:124px;top:27px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_297\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:320px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ANT +B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_298\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:369px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SIG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_299\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(AM/FM)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_300\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_301\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_302\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ANTENNA SUBLEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_303\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:169px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ANTENNA LEAD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_304\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:375px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_305\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_306\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:120px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SCTY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_307\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:172px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_308\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:124px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_309\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:13px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_310\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:13px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_311\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_312\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:240px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_313\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BACK UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_314\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_315\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SCTY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_316\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:235px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_317\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_318\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>Q8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_319\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>Q4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_320\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>Q1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_321\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:133px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>R15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_322\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_323\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:158px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_324\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_325\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:175px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_326\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A17<br></b></nobr>");
write("</p>");
write("<p id=\"p1_327\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>VSP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_328\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:161px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_329\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_330\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_331\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:243px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_332\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:224px;top:114px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_333\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:57px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_334\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:32px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_335\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:32px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_336\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:37px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_337\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:160px;top:27px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_338\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:16px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_339\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:51px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 16 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_340\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:83px;top:26px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_341\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:16px;top:21px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_342\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:25px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 1 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_343\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_344\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:221px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_345\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:34px;top:230px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ILL+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_346\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:222px;top:246px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>AUDIO UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_347\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_348\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:83px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_349\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:87px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_350\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:23px;top:151px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 14 (7.5 A) FUSE <br>(In the under−dash <br>fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_351\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:388px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CRUISE CONTROL <br>SET/RESUME/ <br>CANCEL SWICH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_352\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:468px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_353\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_354\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:238px;top:314px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_355\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:164px;top:305px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No. 14 (7.5 A) FUSE <br>(In the under−dash <br>fuse/relay box)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_356\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:26px;top:330px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}