with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E50J46170400000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:489px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850px;top:484px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:504px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT HEATER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:469px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:443px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:427px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:416px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:416px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:409px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:409px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:870px;top:40px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2 : With OPDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:870px;top:36px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1 : Without OPDS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:353px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:781px;top:324px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:787px;top:186px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:872px;top:129px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:838px;top:227px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:913px;top:512px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G552<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:570px;top:512px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G551<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:584px;top:120px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:129px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:915px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:815px;top:220px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:220px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:255px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:807px;top:280px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:364px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850px;top:353px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:850px;top:324px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:227px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:227px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:239px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:915px;top:409px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:357px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:855px;top:275px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:373px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FRONT PASSENGER'S SEAT HEATER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:160px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:160px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:652px;top:311px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:192px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:567px;top:192px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:572px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:658px;top:176px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:590px;top:176px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862px;top:381px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:862px;top:514px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:524px;top:170px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FRONT PASSENGER'S <br>SEAT HEATER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:342px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:638px;top:126px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.14 (7.5 A) FUSE <br>(UNDER−DASH <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:153px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SEAT <br>HEATER <br>RELAY <br>(LOW)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:887px;top:153px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SEAT <br>HEATER <br>RELAY <br>(HIGH)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:884px;top:116px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>SEAT HEATER <br>RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:555px;top:250px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:604px;top:250px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:664px;top:250px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:332px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:313px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:341px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:104px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>Q16<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:104px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>M5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:73px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>C3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:312px;top:73px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:64px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:44px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>H1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:404px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:404px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:305px;top:112px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:86px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:90px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:90px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:186px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:134px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:330px;top:206px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>OFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:337px;top:176px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:176px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:280px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:192px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>HIGH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:192px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LOW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:149px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:301px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:239px;top:312px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:262px;top:163px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:163px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:436px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:101px;top:367px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>B1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:392px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:409px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:80px;top:372px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:236px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>CUSHION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:224px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:224px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>A2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:404px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:277px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:252px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:130px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DRIVER'S SEAT HEATER RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:214px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:123px;top:214px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:122px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:60px;top:197px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:177px;top:129px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:120px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:120px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:120px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:101px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[ON : 25−35 °C (77−95 °F)]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:108px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[OFF : 46−54 °C (114−129 °F)]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:94px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[OFF : 36−44 °C (97−111 °F)]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:87px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>[ON : 25−35 °C (77−95 °F)]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:101px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BR : BREAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:54px;top:87px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>TH : THERMOSTAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:69px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:86px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:63px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (OP) (80 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:324px;top:509px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G502<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:509px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>G551<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:179px;top:32px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:195px;top:53px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>IG2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:187px;top:43px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:165px;top:49px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:33px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:117px;top:43px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:43px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.1 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:39px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:357px;top:85px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:153px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SEAT <br>HEATER <br>RELAY <br>(HIGH)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:153px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>SEAT <br>HEATER <br>RELAY <br>(LOW)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:129px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>No.14 (7.5 A) FUSE <br>(UNDER−DASH <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:232px;top:342px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DASH LIGHTS <br>BRIGHTNESS <br>CONTROLLER <br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:252px;top:250px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:250px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:170px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>DRIVER'S SEAT <br>HEATER SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:250px;font-weight:normal;font-size:3.0pt;\">");
write("<nobr><b>INDICATOR <br>(LED)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}