with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1108px;\" coordsize=\"950,1108\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1108px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40A14500000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1108px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:888px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:871px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:813px;top:591px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DIMMING CIRCUIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:405px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:405px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:405px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:405px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:534px;top:405px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:37px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>*2 : With security<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:820px;top:28px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>*1 : Without security<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:676px;top:114px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>HORN RELAY *<sup>2</sup><br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:192px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:223px;top:201px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>(15 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>26<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>50<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>73<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>49<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>25<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>74<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>40<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:860px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>28<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ4+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:591px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ4−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ3+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:471px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ3−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ2+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ2−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ1+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ1−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CLSW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:834px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CLSWOFF<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:636px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:645px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>38<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:636px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:645px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>36<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:636px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 (96P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:645px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>84<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:645px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>47<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:636px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:636px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:662px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BKSWNO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:662px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BKSWNC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:662px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>NC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:662px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CANL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:662px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CANH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:516px;top:645px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>48<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:999px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:528px;top:936px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:634px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:578px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:936px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:999px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:999px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:936px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:331px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:384px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT/RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:833px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>INJ2−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:936px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:999px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:142px;top:939px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:955px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:992px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:1066px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:1014px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:282px;top:661px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:619px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRN/BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:146px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:156px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>(100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:517px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:517px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:445px;top:620px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:620px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:574px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G501<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:517px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:582px;top:419px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:254px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:285px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:285px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:871px;top:382px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LIGHTS<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:679px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE CONTROL INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:745px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>12 V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:211px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:144px;top:1014px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:140px;top:1066px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>G401<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:992px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:156px;top:955px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:905px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:548px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:548px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:485px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:219px;top:485px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:201px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>(50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:192px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:88px;top:851px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2 (58P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:162px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:697px;top:162px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:254px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:48px;top:645px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:420px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:419px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:651px;top:419px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:420px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:289px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:300px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IG1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:922px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:293px;top:619px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU/WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:199px;top:574px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:125px;top:620px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:521px;top:517px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:465px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:381px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:143px;top:390px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>(10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:465px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:823px;top:517px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:757px;top:639px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE MAIN INDICATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:591px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>DRIVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:696px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>GAUGE CONTROL MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:39px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:725px;top:562px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CPU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:151px;top:320px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>IGNITION <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:203px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:711px;top:349px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CAN−<br>CEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:751px;top:349px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>RESUME/<br>ACCEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:859px;top:469px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CABLE <br>REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:503px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>BRAKE <br>PEDAL <br>POSITION <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:799px;top:95px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.14 (7.5 A) FUSE <br>(UNDER−DASH <br>FUSE/RELAY BOX)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:665px;top:349px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>SET/<br>DECEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:602px;top:342px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE <br>CONTROL <br>MAIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:417px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−DASH <br>FUSE/RELAY <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:168px;top:964px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CLUTCH <br>PEDAL <br>POSITION <br>SWITCH A <br>(ON : Pedal <br>pressed)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:213px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>HORN <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:522px;top:274px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CRUISE CONTROL <br>COMBINATION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:185px;top:69px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>UNDER−HOOD <br>FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:284px;top:555px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>OUTPUT SHAFT <br>SPEED SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:964px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>CLUTCH <br>PEDAL <br>POSITION <br>SWITCH B <br>(ON : Pedal <br>released)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:294px;top:964px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.1 <br>INJECTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:419px;top:964px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.2 <br>INJECTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:964px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.4 <br>INJECTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:539px;top:964px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>No.3 <br>INJECTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:87px;font-weight:normal;font-size:5.4pt;\">");
write("<nobr><b>MULTIPLEX <br>INTEGRATED <br>CONTROL UNIT *<sup>1</sup><br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}