with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:481px;\" coordsize=\"475,481\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:481px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00K763000Y1283FAAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:481px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:16px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>UNDER-DASH FUSE/RELAY BOX CONNECTOR S (20P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:61px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR WIPER<br>INT/LO SW (ORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:116px;top:79px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GND (BLK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:185px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MIST SW<br>(GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:267px;top:185px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR WIPER<br>HI/LO SW<br>(WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:297px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR WIPER<br>INT/LO SW<br>(ORN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:84px;top:432px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>WIPER/WASHER SWITCH 8P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:450px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:34px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:245px;top:254px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>MIST SW<br>(GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:311px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>FR WIPER<br>HI/LO SW<br>(WHT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:397px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>GND (BLK)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}