with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\" coordsize=\"950,543\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:543px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SWA7EF0A20300000000DBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ROCKER ARM OIL<br>CONTROL VALVE<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 1 INJECTOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 2 INJECTOR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 3 INJECTOR<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:160px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 4 INJECTOR<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:16px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>MAP SENSOR<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:220px;top:147px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 1<br>IGNITION<br>COIL (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:345px;top:147px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 2<br>IGNITION<br>COIL (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:486px;top:147px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 3<br>IGNITION<br>COIL (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:635px;top:148px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 4<br>IGNITION<br>COIL (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:147px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>KNOCK<br>SENSOR<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:75px;top:298px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ALTERNATOR<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:296px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/C PRESSURE<br>SENSOR (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:297px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>EOP SENSOR<br>(15)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:376px;top:298px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>IMT VALVE<br>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:472px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}