with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1040px;\" coordsize=\"950,1040\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1040px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40J36300000000EAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1040px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:928px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:733px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:336px;top:469px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With AUTO A/C)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:748px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With HFT)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:985px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ACC UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:985px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:973px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:973px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>E−PRETENSIONER UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:951px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:469px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With HID)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:66px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:469px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With AFS)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:773px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:813px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:835px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:97px;top:712px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LIN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:334px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:635px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:527px;top:733px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:545px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:545px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:613px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>A20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:635px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:625px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:648px;top:334px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:475px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:498px;top:334px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:633px;top:266px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:332px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:355px;top:334px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>30<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:483px;top:266px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:266px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:266px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:180px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Q8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:89px;top:98px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>K−LINE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:33px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:149px;top:80px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:52px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>: Other communication line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:38px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>: CAN line<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:334px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:356px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:98px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:712px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CAN H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:505px;top:712px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CAN L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:802px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:469px;top:733px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>34<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:511px;top:802px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:905px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ECM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:905px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:916px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>SRS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:939px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>DATA LINK CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:928px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:916px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:402px;top:939px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:226px;top:149px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>Q6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:212px;top:181px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>DATA LINK <br>CONNECTOR <br>(16P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>IMMOBILIZER−<br>KEYLESS <br>CONTROL UNIT<br>(7P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:314px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>CLIMATE <br>CONTROL UNIT <br>(36P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>AUTOMATIC <br>LIGHTING/ <br>RAIN SENSOR <br>(5P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:605px;top:392px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>ADAPTIVE <br>FRONT LIGHTING <br>CONTROL UNIT <br>(40P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:871px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>FRONT <br>PASSENGER'S <br>WINDOW SWITCH <br>(14P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:663px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>POWER WINDOW <br>MASTER SWITCH <br>(22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:670px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>GAUGE CONTROL <br>MODULE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:412px;top:950px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>YAW RATE LATERAL <br>ACCELEERATION SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:609px;top:670px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>HANDS FREE <br>TELEPHONE <br>CONTROL UNIT <br>(22P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:948px;font-weight:normal;font-size:6.8pt;\">");
write("<nobr><b>(With front window <br>AUTO UP/AUTO DOWN function)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}