with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:353px;\" coordsize=\"475,353\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:353px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E1SE10474559771KBAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:353px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:271px;top:18px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:339px;top:39px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:43px;top:30px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:280px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>07LAF-PZ70110<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:173px;top:297px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>07KAF-PS30120<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:267px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>07JAF-SJ80120<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:323px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>07JAF-SJ80110<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:353px;top:15px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>07JAF-SJ80120<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}