with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:831px;\" coordsize=\"950,831\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:831px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E1PE10411200000CAAD03.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:831px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAINSHAFT<br>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:449px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT<br>2ND GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:47px;top:367px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IDLER SHAFT<br>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:282px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IDLER SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:437px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY SHAFT<br>IDLER GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:325px;top:485px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY SHAFT<br>2ND GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:304px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SECONDARY SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:343px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2ND CLUTCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:194px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>COUNTERSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:163px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FINAL DRIVE GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:130px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MAINSHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:745px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TORQUE CONVERTER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:513px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER<br>DRIVE GEAR<br>(HYPOID GEAR)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:821px;top:752px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER<br>OUTPUT SHAFT<br>(HYPOID GEAR)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:566px;top:702px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER (4WD)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:679px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FAINAL DRIVEN GEAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:434px;top:736px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TRANSFER DRIVE GEAR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}