with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:991px;\" coordsize=\"950,991\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:991px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7EL0A14600000000DAAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:991px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:380px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>IGNITION COIL COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:730px;top:464px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:962px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHAIN CASE COVER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:344px;top:876px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT POSITION<br>(CKP) SENSOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:739px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>TENSIONER ARM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:711px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT PULLEY<br><a href=\"javascript:CtsProc('0','000000000001685','i000')\"></b>Removal/Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:128px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CYLINDER HEAD COVER<br><a href=\"javascript:CtsProc('0','000000000001672','i000')\"></b>Removal,</a><br><a href=\"javascript:CtsProc('0','000000000001673','i000')\">Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:537px;top:203px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN<br><a href=\"javascript:CtsProc('0','000000000001683','i000')\"></b>Removal,</a><br><a href=\"javascript:CtsProc('0','000000000001684','i000')\">Installation,</a><br><a href=\"javascript:CtsProc('0','000000000003866','i000')\">Inspection,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:794px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>VARIABLE VALVE<br>TIMING CONTROL<br>(VTC) OIL CONTROL<br>SOLENOID VALVE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:709px;top:882px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CRANKSHAFT PULLEY BOLT<br><a href=\"javascript:CtsProc('0','000000000001685','i000')\"></b>Removal/Installation,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:918px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CKP PULSE PLATE<br><a href=\"javascript:CtsProc('0','000000000001724','i000')\"></b>Replacement,</a><br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:17px;top:848px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>AUTO-TENSIONER<br><a href=\"javascript:CtsProc('0','000000000001686','i000')\"></b>Removal/Installation,<br></a><br></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:364px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN GUIDE B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:458px;top:849px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CHAIN CASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:408px;top:826px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>O-RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:414px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAM CHAIN GUIDE A<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}