with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:687px;\" coordsize=\"950,687\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:687px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R11100000000YCAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:687px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:40px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PASSENGER'S AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:104px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SRS UNIT<br>(With built-in<br>the sensor)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:761px;top:217px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE<br>IMPACT SENSOR <br>(FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:608px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE IMPACT SENSOR<br>(FIRST)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:229px;top:40px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CABLE REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:116px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OPDS SENSOR/<br>SEAT-BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:593px;top:526px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ODS UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:278px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE<br>SEAT BELT<br>TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:498px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:405px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DATA LINK<br>CONNECTOR<br>(DLC)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:21px;top:79px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MEMORY ERASE<br>SIGNAL (MES)<br>CONNECTOR (2P)<br>(YELLOW)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:503px;top:579px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE SEAT BELT TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:175px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:316px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DRIVER'S AIRBAG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:181px;top:591px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LEFT SIDE SEAT BELT<br>OUTER LAP TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:640px;top:483px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT PASSENGER'S<br>SEAT SITTING SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:700px;top:433px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>RIGHT SIDE SEAT BELT<br>OUTER LAP TENSIONER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:657px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>LHD model is shown, RHD model is similar.<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}