with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E00J18500024101KBAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:86px;top:31px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL CONSUMPTION<br>STICKER (KD model, Left side)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:378px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Unit: mm (in.)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:603px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1.5<br>(0.06)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:167px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4WD STICKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:201px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>i-VTEC STICKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:562px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5 (0.2)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:76px;top:419px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR QUARTER GLASS (Inside)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:90px;top:691px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ALIGNMENT MARK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:259px;top:687px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FUEL CONSUMPTION<br>STICKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:628px;top:420px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>i-VTEC STICKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:419px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>APPLICATION TAPE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:497px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1.5<br>(0.06)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:500px;top:687px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ALIGNMENT MARK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:707px;top:614px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Edge of the<br>rear window<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:754px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>KM model<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:802px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ALIGNMENT MARK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:494px;top:818px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4WD STICKER<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:1008px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>APPLICATION TAPE<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:366px;top:938px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>Edge of the<br>rear window<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}