with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E20K722000R7114FAAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:227px;top:165px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S1<br>(BRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:132px;top:166px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S3 (PNK)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:279px;top:165px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>R1 (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:83px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>R2 (GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:135px;top:82px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S4 (PUR)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:126px;top:59px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S2 (LT GRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:32px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>EPS CONTROL UNIT CONNECTOR D (20P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:271px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of female terminals<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}