with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:591px;\" coordsize=\"950,591\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:591px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00D10600000000CAAD05.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:591px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:136px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MODULATOR UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:322px;top:396px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RESERVOIR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:257px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>FL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:679px;top:506px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:425px;top:46px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MASTER CYLINDER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:611px;top:550px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IN: INLET SOLENOID VALVE (NORMALLY OPEN)<br>OUT: OUTLET SOLENOID VALVE (NORMALLY CLOSED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:454px;top:352px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>MOTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:364px;top:344px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:227px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:230px;top:227px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:331px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:227px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:622px;top:331px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:865px;top:227px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:344px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>PUMP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:563px;top:396px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>RESERVOIR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:220px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>DAMPING<br>CHAMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:331px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:779px;top:331px;font-weight:normal;font-size:6.5pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}