with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1039px;\" coordsize=\"950,1039\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1039px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R51100000000YDAD09.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1039px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:164px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL ARCH <br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:30px;top:564px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:744px;top:34px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:812px;top:212px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:481px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR<br>WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:601px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR INNER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:260px;top:260px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:331px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: X]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:290px;top:234px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[Y]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:346px;top:870px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>[VIEW: Y]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:36px;top:625px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:150px;top:423px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL ARCH <br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:366px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:850px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:587px;top:899px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:217px;top:989px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br>LOWER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:628px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br>(REAR WHEELHOUSE<br>STIFFENER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:797px;top:753px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME A<br>EXTENSION REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:739px;top:810px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME A<br>EXTENSION REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:459px;top:978px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR DAMPER<br>BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:760px;top:943px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR CROSS BEAM<br>MOUNT BRACKET<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:56px;top:811px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br>(REAR WHEELHOUSE<br>STIFFENER)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:757px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL ARCH<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:46px;top:464px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL ARCH <br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:493px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:568px;top:410px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER<br>PANEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:301px;top:479px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR <br>INNER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:900px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL EXTENSION<br>FLANGE END<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:80px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br>EXTENSION<br>FLANGE END<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:644px;top:403px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR <br>INNER<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}