with(document) {
write("<v:group id=\"group6\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:559px;\" coordsize=\"950,559\">");
write("<v:rect id=\"rect6\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:559px;\">");
write("<img id=\"img6\" name=\"PrtImgId\" src=\"../img/SWA7E80A20300000000DBAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:559px;border-color:#ffffff\">");
write("<p id=\"p6_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:57px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ROCKER ARM OIL<br>CONTROL VALVE<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:242px;top:18px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ROCKER ARM<br>OIL PRESSURE<br>SWTCH (2)<br>(KD model)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:407px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 1<br>IGNITION<br>COIL (3)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 2<br>IGNITION<br>COIL (4)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:662px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 3<br>IGNITION<br>COIL (5)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:790px;top:17px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 4<br>IGNITION<br>COIL (6)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:58px;top:173px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 1 INJECTOR<br>(7)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:203px;top:173px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 2 INJECTOR<br>(8)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:349px;top:173px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 3 INJECTOR<br>(9)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:495px;top:173px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 4 INJECTOR<br>(10)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:173px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>KNOCK<br>SENSOR<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:802px;top:173px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ALTERNATOR<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:310px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/C PRESSURE<br>SENSOR (13)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:237px;top:310px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>CKP SENSOR<br>(14)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:297px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>VTC OIL<br>CONTROL<br>SOLENOID<br>VALVE (15)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:547px;top:297px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>OIL<br>PRESSURE<br>SWITCH<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:309px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>PSP SWITCH<br>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p6_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:494px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}