with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:1103px;\" coordsize=\"950,1103\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:1103px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00B20200019101MEAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:1103px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:300px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER MOUNTING BEARING<br></b>Check for any play or roughness.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:219px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BUMP STOP<br></b>Check for weakness and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:693px;top:738px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER UNIT<br></b>Check for oil leaks, gas leaks, <br>and smooth operation.<br></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:692px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:53px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SELF-LOCKING NUT<br>12 x 1.25 mm<br>44 N·m <br>(4.5 kgf·m, 33 lbf·ft)<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:469px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER SPRING MOUNTING CUSHION<br></b>Check for deterioration and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:207px;top:653px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER SPRING<br></b>Check for weakened <br>compression and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:292px;top:156px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DAMPER MOUNTING BASE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:171px;top:925px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>LOWER SPRING SEAT<br></b>Check for deterioration and damage.<br></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:382px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>UPPER SPRING SEAT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}