with(document) {
write("<v:group id=\"group18\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:735px;\" coordsize=\"950,735\">");
write("<v:rect id=\"rect18\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:735px;\">");
write("<img id=\"img18\" name=\"PrtImgId\" src=\"../img/SWA7E70A20300000000DBAD18.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:735px;border-color:#ffffff\">");
write("<p id=\"p18_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:839px;top:321px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>JUNCTION <br>BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p18_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:671px;top:709px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p18_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:677px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>ENGINE COMPARTMENT<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p18_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:635px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DASHBOARD<br>WIRE HARNESS<br></b></nobr>");
write("</p>");
write("<p id=\"p18_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:22px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p18_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:391px;top:21px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p18_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:460px;top:15px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p18_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:36px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p18_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:418px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>16<br></b></nobr>");
write("</p>");
write("<p id=\"p18_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:773px;top:456px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>17<br></b></nobr>");
write("</p>");
write("<p id=\"p18_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:320px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p18_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:365px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>18<br></b></nobr>");
write("</p>");
write("<p id=\"p18_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:716px;top:290px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p18_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:766px;top:94px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p18_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:764px;top:150px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>12<br></b></nobr>");
write("</p>");
write("<p id=\"p18_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:829px;top:233px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p18_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:774px;top:214px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p18_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:828px;top:273px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>15<br></b></nobr>");
write("</p>");
write("<p id=\"p18_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:783px;top:628px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p18_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:704px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p18_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:700px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>23<br></b></nobr>");
write("</p>");
write("<p id=\"p18_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:737px;top:83px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p18_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:583px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p18_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:626px;top:37px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p18_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:682px;top:51px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p18_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:249px;top:25px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p18_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:710px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}