with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:320px;\" coordsize=\"475,320\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:320px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00J36200000000FEAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:320px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:121px;top:50px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>Navi  System  Link<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:352px;top:52px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Return<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:343px;top:229px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Exit Diag<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:335px;top:95px;font-weight:normal;font-size:8.3pt;\">");
write("<nobr><b>Detecting..<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:143px;font-weight:normal;font-size:8.9pt;\">");
write("<nobr><b>Navi.ECU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:97px;font-weight:normal;font-size:6.1pt;\">");
write("<nobr><b>GPS Ant.<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:181px;font-weight:normal;font-size:6.1pt;\">");
write("<nobr><b>Display<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:181px;font-weight:normal;font-size:6.1pt;\">");
write("<nobr><b>Radio<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:196px;font-weight:normal;font-size:6.1pt;\">");
write("<nobr><b>BACK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:148px;top:98px;font-weight:normal;font-size:6.1pt;\">");
write("<nobr><b>Air-Con<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:181px;font-weight:normal;font-size:6.1pt;\">");
write("<nobr><b>R-Camera<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}