with(document) {
write("<v:group id=\"group7\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:543px;\" coordsize=\"950,543\">");
write("<v:rect id=\"rect7\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:543px;\">");
write("<img id=\"img7\" name=\"PrtImgId\" src=\"../img/SWA7E70A20300000000DBAD07.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:543px;border-color:#ffffff\">");
write("<p id=\"p7_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:66px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ROCKER ARM OIL<br>CONTROL VALVE<br>(1)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 1 INJECTOR<br>(2)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:415px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 2 INJECTOR<br>(3)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:561px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 3 INJECTOR<br>(4)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:166px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 4 INJECTOR<br>(6)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:746px;top:30px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>MAP SENSOR<br>(5)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:148px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 1<br>IGNITION<br>COIL (7)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:382px;top:148px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 2<br>IGNITION<br>COIL (8)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:510px;top:148px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 3<br>IGNITION<br>COIL (9)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:637px;top:148px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>No. 4<br>IGNITION<br>COIL (10)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:778px;top:167px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>KNOCK<br>SENSOR<br>(11)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:74px;top:304px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ALTERNATOR<br>(12)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:247px;top:289px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>ENGINE<br>OIL LEVEL<br>SENSOR (13)<br>(KG, KS models)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:371px;top:303px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>A/C PRESSURE<br>SENSOR (14)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:506px;top:303px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>3P CONNECTOR<br>(15)<br>(KG, KS models)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:788px;top:303px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>EOP SNSOR<br>(17)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:654px;top:303px;font-weight:normal;font-size:7.4pt;\">");
write("<nobr><b>IMT VALVE<br>(16)<br></b></nobr>");
write("</p>");
write("<p id=\"p7_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:0px;top:480px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>NOTE:<br>· Connector with male terminals (double outline): view from terminal side<br>· Connector with female terminals (single outline): view from wire side<br></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}