with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:433px;\" coordsize=\"475,433\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:433px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E3AK72100090301FAAD08.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:433px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:270px;top:117px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>INJ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:103px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Wire side of<br>female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:2px;top:263px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>ECM/PCM<br>CONNECTOR<br>C (44P)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:115px;top:400px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b></b>Terminal side of female terminals<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:139px;top:15px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>INJECTOR 2P CONNECTOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:169px;top:209px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>INJ2 (RED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:209px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>INJ3 (BLU)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:146px;top:237px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>INJ1 (BRN)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:315px;top:237px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>INJ4 (YEL)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}