with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:475px; height:657px;\" coordsize=\"475,657\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:475px;height:657px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E2PE10400013012KBAD01.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:475px;height:657px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:438px;top:73px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:79px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>D<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:439px;top:558px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>E<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:340px;top:136px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:409px;top:46px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:326px;top:520px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>F<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:347px;top:478px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>G<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:414px;top:582px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>H<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:550px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>I<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:300px;top:86px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>J<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:216px;top:75px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Z<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:205px;top:198px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>L<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:273px;top:74px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>M<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:236px;top:116px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>N<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:569px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>O<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:618px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>P<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:253px;top:621px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Q<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:298px;top:604px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>R<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:214px;top:511px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>S<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:163px;top:551px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>T<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:55px;top:546px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>U<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:96px;top:566px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>V<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:133px;top:561px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>W<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:87px;top:439px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>X<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:111px;top:12px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>Y<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:13px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>CC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:182px;top:33px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>BB<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:206px;top:52px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>AA<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:69px;top:104px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>DD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:191px;top:146px;font-weight:normal;font-size:9.2pt;\">");
write("<nobr><b>K<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}