with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:554px;\" coordsize=\"950,554\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:554px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E40J14235000000EAAD90.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:554px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:858px;top:19px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>[    ]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:19px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: RHD model<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:795px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:765px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:613px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:580px;top:55px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MUTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ICON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>8<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:685px;top:142px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B18<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:656px;top:142px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:202px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:202px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ICON<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MUTE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:675px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:103px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:103px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:645px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>L+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:674px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>L−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>R−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:109px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>R+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:103px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:706px;top:103px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>FR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIG−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:731px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIG SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:770px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:763px;top:230px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:283px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC IN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:686px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:719px;top:283px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:283px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:747px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:202px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:735px;top:202px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:126px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>TELEM<br></b></nobr>");
write("</p>");
write("<p id=\"p1_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:704px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIG+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:732px;top:132px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SIG−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:869px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>: Shielding<br></b></nobr>");
write("</p>");
write("<p id=\"p1_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:703px;top:410px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ROOF CONSOLE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:749px;top:334px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:756px;top:360px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>9<br></b></nobr>");
write("</p>");
write("<p id=\"p1_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:334px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:728px;top:360px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>6<br></b></nobr>");
write("</p>");
write("<p id=\"p1_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:677px;top:116px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:92px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:84px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:92px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:734px;top:84px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>YEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:673px;top:84px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:681px;top:92px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:641px;top:84px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:653px;top:92px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>A12<br></b></nobr>");
write("</p>");
write("<p id=\"p1_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:142px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B10<br></b></nobr>");
write("</p>");
write("<p id=\"p1_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:142px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:713px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>7<br></b></nobr>");
write("</p>");
write("<p id=\"p1_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:742px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:691px;top:316px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:699px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>20<br></b></nobr>");
write("</p>");
write("<p id=\"p1_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:280px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:586px;top:24px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>LEFT TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:769px;top:24px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>RIGHT TWEETER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:647px;top:18px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>LEFT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:708px;top:18px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>RIGHT FRONT <br>DOOR SPEAKER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:720px;top:394px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>NAVIGATION/HFT <br>MICROPHONE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:102px;top:536px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>[G502]<br></b></nobr>");
write("</p>");
write("<p id=\"p1_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:96px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:289px;top:39px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>C2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:75px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>E14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:174px;top:39px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:153px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>R15<br></b></nobr>");
write("</p>");
write("<p id=\"p1_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:153px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>Q1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RADIO<br></b></nobr>");
write("</p>");
write("<p id=\"p1_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BACK UP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:269px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>+B<br></b></nobr>");
write("</p>");
write("<p id=\"p1_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:303px;top:137px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MICU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:299px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−DASH FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:308px;top:37px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 34 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:279px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:302px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:309px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>4<br></b></nobr>");
write("</p>");
write("<p id=\"p1_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:368px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:380px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:328px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>19<br></b></nobr>");
write("</p>");
write("<p id=\"p1_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:103px;top:530px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>G503<br></b></nobr>");
write("</p>");
write("<p id=\"p1_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:337px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:145px;top:337px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>13<br></b></nobr>");
write("</p>");
write("<p id=\"p1_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:152px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>14<br></b></nobr>");
write("</p>");
write("<p id=\"p1_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:141px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>B−CAN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:289px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GND<br></b></nobr>");
write("</p>");
write("<p id=\"p1_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:285px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>STRG<br></b></nobr>");
write("</p>");
write("<p id=\"p1_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:254px;top:290px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SW<br></b></nobr>");
write("</p>");
write("<p id=\"p1_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OUT+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:277px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OUT−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:271px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:159px;top:198px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:163px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:154px;top:169px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OUT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:118px;top:152px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>NAVIGATION UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:169px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:129px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OUT−<br></b></nobr>");
write("</p>");
write("<p id=\"p1_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:175px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>OUT+<br></b></nobr>");
write("</p>");
write("<p id=\"p1_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:104px;top:169px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>MIC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:167px;top:185px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:185px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:185px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>D2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:193px;top:80px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:333px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:105px;top:230px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:51px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ACC<br></b></nobr>");
write("</p>");
write("<p id=\"p1_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:225px;top:39px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BAT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:266px;top:45px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:194px;top:45px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:73px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 16 (10 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>UNDER−HOOD FUSE/RELAY BOX<br></b></nobr>");
write("</p>");
write("<p id=\"p1_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:127px;top:37px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 2 (IG) (50 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:42px;top:32px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BATTERY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:215px;top:25px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>IGNITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:73px;top:36px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>No. 1 (BAT) (100 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:280px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>HANDS FREE TELEPHONE  CONTROL UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:342px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:281px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>11<br></b></nobr>");
write("</p>");
write("<p id=\"p1_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:272px;top:245px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p1_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>21<br></b></nobr>");
write("</p>");
write("<p id=\"p1_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:138px;top:260px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>22<br></b></nobr>");
write("</p>");
write("<p id=\"p1_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:130px;top:230px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:396px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1<br></b></nobr>");
write("</p>");
write("<p id=\"p1_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:367px;top:478px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p1_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:484px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p1_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:316px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p1_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:396px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>3<br></b></nobr>");
write("</p>");
write("<p id=\"p1_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:265px;top:420px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>1 kΩ<br></b></nobr>");
write("</p>");
write("<p id=\"p1_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:416px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>47 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:286px;top:426px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>180 Ω<br></b></nobr>");
write("</p>");
write("<p id=\"p1_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:359px;top:366px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p1_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:263px;top:300px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>2<br></b></nobr>");
write("</p>");
write("<p id=\"p1_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:277px;top:348px;font-weight:normal;font-size:3.4pt;\">");
write("<nobr><b>CABLE REEL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:288px;top:446px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>ON <br>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:313px;top:446px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>OFF <br>HOOK<br></b></nobr>");
write("</p>");
write("<p id=\"p1_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:368px;top:462px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>LIGHT <br>(LED)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:354px;top:515px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUDIO <br>REMOTE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:134px;top:386px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>MULTIPLEX <br>INTEGRATED <br>CONTROL <br>UNIT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:356px;top:320px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUDIO <br>REMOTE <br>SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:234px;top:480px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>HFT−VOICE <br>CONTROL SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p1_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:297px;top:515px;font-weight:normal;font-size:3.3pt;\">");
write("<nobr><b>AUDIO  <br>REMOTE <br>SWITCH<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}