with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:975px;\" coordsize=\"950,975\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:975px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E00R51100000000YDAD06.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:975px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:304px;top:66px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR WHEEL ARCH<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:816px;top:149px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR <br>WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:814px;top:448px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:93px;top:858px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:639px;top:913px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:837px;top:357px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:784px;top:865px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:287px;top:834px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLOOR CAP<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:278px;top:934px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:749px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FRONT FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:71px;top:657px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL <br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:32px;top:554px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INSIDE<br>SILL<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:688px;top:285px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME A<br></b></nobr>");
write("</p>");
write("<p id=\"p1_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:453px;top:18px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR <br>WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:550px;top:154px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR  WHEELHOUSE<br></b></nobr>");
write("</p>");
write("<p id=\"p1_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:120px;top:100px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL<br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:70px;top:364px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:485px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:81px;top:204px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FLOOR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:714px;top:313px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:649px;top:762px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>MIDDLE FLOOR<br>CROSS-MEMBER STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:597px;top:27px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL ARCH<br>EXTENSION REAR<br></b></nobr>");
write("</p>");
write("<p id=\"p1_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:680px;top:181px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>REAR FRAME<br>UPPER<br>STIFFENER<br></b></nobr>");
write("</p>");
write("<p id=\"p1_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:99px;top:545px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL <br>EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:72px;top:327px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SIDE SILL EXTENSION<br></b></nobr>");
write("</p>");
write("<p id=\"p1_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:20px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>WHEEL ARCH<br>EXTENSION REAR<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}