with(document) {
write("<v:group id=\"group2\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:640px; height:950px;\" coordsize=\"640,950\">");
write("<v:rect id=\"rect2\" name=\"PrtRectId\"class=\"drag\"  style=\"width:640px;height:950px;\">");
write("<img id=\"img2\" name=\"PrtImgId\" src=\"../img/SWA7E50000000000000EBA203.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:640px;height:950px;border-color:#ffffff\">");
write("<p id=\"p2_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>B<br></b></nobr>");
write("</p>");
write("<p id=\"p2_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:535px;top:44px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>C<br></b></nobr>");
write("</p>");
write("<p id=\"p2_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:632px;top:858px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ALTERNATOR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:636px;top:111px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>105<br></b></nobr>");
write("</p>");
write("<p id=\"p2_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:623px;top:85px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.15 (7.5 A) <br>FUSE <br>(3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:284px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Audio unit<br></b></nobr>");
write("</p>");
write("<p id=\"p2_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:284px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:284px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(21−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:284px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:502px;top:293px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*15<br></b></nobr>");
write("</p>");
write("<p id=\"p2_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:482px;top:293px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(22−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:275px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(21−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:275px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*14<br></b></nobr>");
write("</p>");
write("<p id=\"p2_14\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:266px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*16<br></b></nobr>");
write("</p>");
write("<p id=\"p2_15\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:266px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(20−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_16\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:408px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_17\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:408px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_18\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:417px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_19\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:513px;top:417px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_20\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:390px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_21\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:390px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_22\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:399px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_23\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:517px;top:399px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_24\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:373px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_25\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:372px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_26\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:509px;top:381px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_27\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:490px;top:382px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_28\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:355px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_29\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:355px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_30\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:504px;top:363px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_31\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:485px;top:364px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_32\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:448px;top:578px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(With cruise control)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_33\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-66px;top:838px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_34\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-66px;top:847px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_35\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:847px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_36\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-49px;top:838px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_37\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:304px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_38\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:231px;top:109px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_39\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:542px;top:310px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*12<br></b></nobr>");
write("</p>");
write("<p id=\"p2_40\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:310px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Daytime running light relay (3−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_41\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:310px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_42\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:160px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>A/T gear position indicator panel light (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_43\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:231px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>CMBS OFF switch light (17−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_44\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:231px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_45\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:248px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_46\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:248px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>HVAC control unit (19−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_47\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:257px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Navigation unit (20−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_48\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:257px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_49\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:151px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Ambient light (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_50\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:151px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_51\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:346px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_52\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:346px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_53\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:533px;top:337px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_54\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:514px;top:337px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_55\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:320px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_56\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:319px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*11<br></b></nobr>");
write("</p>");
write("<p id=\"p2_57\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:538px;top:328px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*13<br></b></nobr>");
write("</p>");
write("<p id=\"p2_58\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:518px;top:328px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_59\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:186px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Front passenger'seat heater switches light (13−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_60\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:186px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_61\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:432px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ACC RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_62\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:530px;top:512px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(With ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_63\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:463px;top:534px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(Without ACC)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_64\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Brake lights (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_65\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:555px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>108<br></b></nobr>");
write("</p>");
write("<p id=\"p2_66\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:630px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_67\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:385px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_68\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:643px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_69\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:643px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_70\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:625px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_71\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:625px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_72\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:625px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_73\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:497px;top:634px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_74\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:481px;top:634px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_75\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:625px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ECM/PCM <br></b></nobr>");
write("</p>");
write("<p id=\"p2_76\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:607px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(5−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_77\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:607px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*10<br></b></nobr>");
write("</p>");
write("<p id=\"p2_78\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:491px;top:598px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*9<br></b></nobr>");
write("</p>");
write("<p id=\"p2_79\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:474px;top:599px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(4−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_80\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:630px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>110<br></b></nobr>");
write("</p>");
write("<p id=\"p2_81\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:531px;top:747px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(With TSA)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_82\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:807px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_83\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-56px;top:807px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_84\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-38px;top:807px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_85\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-38px;top:816px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_86\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-56px;top:816px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_87\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:763px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_88\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-47px;top:763px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_89\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-47px;top:754px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_90\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-65px;top:754px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_91\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-60px;top:696px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_92\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-43px;top:696px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*8<br></b></nobr>");
write("</p>");
write("<p id=\"p2_93\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-43px;top:705px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*7<br></b></nobr>");
write("</p>");
write("<p id=\"p2_94\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-60px;top:705px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(9−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_95\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-56px;top:226px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(14−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_96\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-34px;top:226px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_97\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-34px;top:217px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_98\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-56px;top:217px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_99\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_100\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:838px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_101\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:892px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>115<br></b></nobr>");
write("</p>");
write("<p id=\"p2_102\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:856px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_103\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:39px;top:807px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>69<br></b></nobr>");
write("</p>");
write("<p id=\"p2_104\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:779px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_105\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:856px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>114<br></b></nobr>");
write("</p>");
write("<p id=\"p2_106\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:856px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PNK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_107\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_108\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:891px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>PUR<br></b></nobr>");
write("</p>");
write("<p id=\"p2_109\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:851px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_110\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:869px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_111\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:789px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_112\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:441px;top:771px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_113\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:416px;top:838px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>G302<br></b></nobr>");
write("</p>");
write("<p id=\"p2_114\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:807px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLK<br></b></nobr>");
write("</p>");
write("<p id=\"p2_115\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:807px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_116\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:79px;top:754px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>33<br></b></nobr>");
write("</p>");
write("<p id=\"p2_117\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:776px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ORN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_118\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:776px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>113<br></b></nobr>");
write("</p>");
write("<p id=\"p2_119\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:147px;top:725px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_120\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:128px;top:754px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>45<br></b></nobr>");
write("</p>");
write("<p id=\"p2_121\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:776px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_122\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:479px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ACC unit (17−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_123\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:488px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Brake lights (10−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_124\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:488px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_125\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:719px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>112<br></b></nobr>");
write("</p>");
write("<p id=\"p2_126\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:683px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>111<br></b></nobr>");
write("</p>");
write("<p id=\"p2_127\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:599px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ECM/PCM <br></b></nobr>");
write("</p>");
write("<p id=\"p2_128\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:599px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>109<br></b></nobr>");
write("</p>");
write("<p id=\"p2_129\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:479px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_130\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:484px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>107<br></b></nobr>");
write("</p>");
write("<p id=\"p2_131\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:448px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>ACC unit (17−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_132\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:448px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>106<br></b></nobr>");
write("</p>");
write("<p id=\"p2_133\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:683px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_134\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:683px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_135\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:709px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_136\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:727px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_137\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:718px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_138\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:599px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_139\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:323px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_140\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:483px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_141\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:209px;top:598px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_142\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:108px;top:544px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_143\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:572px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>53<br></b></nobr>");
write("</p>");
write("<p id=\"p2_144\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_145\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:492px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT GRN<br></b></nobr>");
write("</p>");
write("<p id=\"p2_146\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:59px;top:371px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*1<br></b></nobr>");
write("</p>");
write("<p id=\"p2_147\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:41px;top:400px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_148\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:35px;top:430px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_149\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:208px;top:474px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>WHT<br></b></nobr>");
write("</p>");
write("<p id=\"p2_150\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:204px;top:448px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_151\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:329px;top:448px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_152\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:85px;top:430px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>LT BLU<br></b></nobr>");
write("</p>");
write("<p id=\"p2_153\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:92px;top:400px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>60<br></b></nobr>");
write("</p>");
write("<p id=\"p2_154\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:112px;top:371px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*2<br></b></nobr>");
write("</p>");
write("<p id=\"p2_155\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:408px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_156\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:390px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_157\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:372px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_158\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:355px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_159\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:337px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_160\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:319px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_161\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:213px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_162\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:204px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_163\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:195px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_164\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:124px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_165\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:222px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_166\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:160px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_167\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:115px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_168\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:133px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_169\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:239px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_170\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:142px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_171\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:177px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_172\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:266px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_173\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:446px;top:168px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>·<br></b></nobr>");
write("</p>");
write("<p id=\"p2_174\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:315px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>105<br></b></nobr>");
write("</p>");
write("<p id=\"p2_175\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:424px;top:120px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>104<br></b></nobr>");
write("</p>");
write("<p id=\"p2_176\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:95px;top:94px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>103<br></b></nobr>");
write("</p>");
write("<p id=\"p2_177\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:825px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Headlight washer control unit (11−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_178\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:807px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right headlight (low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_179\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:305px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.15 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_180\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:197px;top:110px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.14 (7.5 A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_181\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:408px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left license plate light<br></b></nobr>");
write("</p>");
write("<p id=\"p2_182\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:337px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left front position light <br></b></nobr>");
write("</p>");
write("<p id=\"p2_183\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:355px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p2_184\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:195px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Power mirror switch light (15−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_185\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:115px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Headlight leveling switch light (9−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_186\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:390px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right license plate light <br></b></nobr>");
write("</p>");
write("<p id=\"p2_187\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:372px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right taillight<br></b></nobr>");
write("</p>");
write("<p id=\"p2_188\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:204px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Sunshade switch light (With sunshade) (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_189\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:133px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Hazard warning switch light (10−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_190\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:239px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Climate control unit light (18−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_191\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:142px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Glove box light (11−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_192\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:319px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right front position light<br></b></nobr>");
write("</p>");
write("<p id=\"p2_193\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:315px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>RED<br></b></nobr>");
write("</p>");
write("<p id=\"p2_194\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:328px;top:120px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>GRY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_195\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:838px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left headlight (low beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_196\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:754px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left headlight (high beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_197\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:696px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right headlight (high beam)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_198\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:669px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (+B H/L LO) (6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_199\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:599px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (+B H/L HI) (6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_200\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:621px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (+B SMALL) (6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_201\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:643px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (+B RR FOG) (6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_202\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:213px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Sunroof switch light (With sunroof) (15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_203\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:177px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Driver'seat heater switches light (13−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_204\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:266px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Steering switches light<br></b></nobr>");
write("</p>");
write("<p id=\"p2_205\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:168px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Parking/back−up sensor switch light (12−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_206\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:874px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (+B HAZARD) (6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_207\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:222px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA OFF switch light (16−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_208\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:452px;top:124px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>AFS  OFF switch light (10−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_209\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-33px;top:146px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*6<br></b></nobr>");
write("</p>");
write("<p id=\"p2_210\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-29px;top:137px;font-weight:normal;font-size:3.5pt;\">");
write("<nobr><b>*5<br></b></nobr>");
write("</p>");
write("<p id=\"p2_211\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:293px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_212\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:137px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Sunshade control unit/motor (15−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_213\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:217px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Power window master switch<br></b></nobr>");
write("</p>");
write("<p id=\"p2_214\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:359px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left rear power window switch (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_215\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:337px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right rear power window switch (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_216\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:257px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Front passenger's power window switch (14−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_217\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:164px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Super locking relay (KE model) (6−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_218\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-2px;top:228px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*3<br></b></nobr>");
write("</p>");
write("<p id=\"p2_219\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:146px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Sunroof control unit/motor (15−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_220\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:186px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (+B DR LOCK) (6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_221\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:315px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Power window master switch (14−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_222\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-134px;top:452px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU (6−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_223\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:483px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Front passenger's power window switch (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_224\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:514px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right rear power window switch (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_225\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:545px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left rear power window switch (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_226\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-2px;top:410px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>*4<br></b></nobr>");
write("</p>");
write("<p id=\"p2_227\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-558px;top:22px;font-weight:normal;font-size:7.0pt;\">");
write("<nobr><b>Under−dash Fuse/Relay Box, Starter, Fuel Pump, Alternator<br></b></nobr>");
write("</p>");
write("<p id=\"p2_228\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:554px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left rear power window motor <br>(Via power window master switch) (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_229\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:523px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right rear power window motor <br>(Via power window master switch) (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_230\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:-128px;top:492px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Front passenger's power window motor <br>(Via power window master switch) (14−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_231\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:109px;top:105px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>(Fuse/relay <br>box socket)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_232\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:91px;top:74px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>MICU <br>(6−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_233\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:373px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.22 (7.5 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_234\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:24px;top:373px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.12 (15 A) <br>FUSE <br>(1−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_235\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:78px;top:546px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.3 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_236\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:531px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRAKE PEDAL <br>POSITION SWITCH<br></b></nobr>");
write("</p>");
write("<p id=\"p2_237\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:660px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>BRAKE LIGHT <br>RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_238\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:678px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT <br>(16−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_239\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:714px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>VSA MODULATOR−CONTROL UNIT <br>(16−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_240\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:246px;top:747px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>POWER MIRROR <br>DEFOGGER RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_241\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:113px;top:728px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.36 (10 A) <br>FUSE <br>(2−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_242\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:771px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right power mirrow defogger <br>(15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_243\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:64px;top:721px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>REAR WINDOW <br>DEFOGGER <br>RELAY <br>(1−D)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_244\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:789px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left power mirrow defogger <br>(15−A)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_245\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:869px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Left front fog light <br>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_246\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:851px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Right front fog light <br>(10−B)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_247\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:29px;top:781px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>No.6 (20 A) <br>FUSE <br>(2−C)<br></b></nobr>");
write("</p>");
write("<p id=\"p2_248\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:255px;top:827px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>FRONT FOG <br>LIGHT RELAY<br></b></nobr>");
write("</p>");
write("<p id=\"p2_249\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:447px;top:807px;font-weight:normal;font-size:4.2pt;\">");
write("<nobr><b>Climate control unit <br>(18−B)<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}