with(document) {
write("<v:group id=\"group1\"  name=\"PrtGrpId\" class=\"drag\" style=\"position:relative; width:950px; height:735px;\" coordsize=\"950,735\">");
write("<v:rect id=\"rect1\" name=\"PrtRectId\"class=\"drag\"  style=\"width:950px;height:735px;\">");
write("<img id=\"img1\" name=\"PrtImgId\" src=\"../img/SWA7E50E16236500000LDAD02.PNG\" border=\"1\" class=\"drag\" style=\"position:absolute;left:0px;top:0px;width:950px;height:735px;border-color:#ffffff\">");
write("<p id=\"p1_1\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:68px;top:461px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>SET RING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_2\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:77px;top:313px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>OUTER SEAL<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_3\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:100px;top:264px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>EXTERNAL SNAP RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_4\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:429px;top:160px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTERMEDIATE <br>SHAFT BEARING<br></b>Replace.<br></nobr>");
write("</p>");
write("<p id=\"p1_5\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:387px;top:16px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>DOWEL BOLTS<br>10 x 1.25 mm<br>39 N·m <br>(4.0 kgf·m, 29 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_6\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:186px;top:39px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>FLANGE BOLT<br>10 x 1.25 mm<br>39 N·m <br>(4.0 kgf·m, 29 lbf·ft)<br></b></nobr>");
write("</p>");
write("<p id=\"p1_7\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:378px;top:442px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTERNAL <br>SNAP RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_8\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:705px;top:307px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTERMEDIATE SHAFT<br></b></nobr>");
write("</p>");
write("<p id=\"p1_9\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:729px;top:80px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>INTERMEDIATE SHAFT RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_10\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:553px;top:361px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BEARING SUPPORT RING<br></b></nobr>");
write("</p>");
write("<p id=\"p1_11\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:435px;top:669px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b></b>Pack the interior <br>of the outer seal.<br></nobr>");
write("</p>");
write("<p id=\"p1_12\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:659px;top:527px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>HEAT SHIELD<br></b></nobr>");
write("</p>");
write("<p id=\"p1_13\" name=\"PrtPId\" class=\"drag\" style=\"position:absolute;left:274px;top:491px;font-weight:normal;font-size:8.6pt;\">");
write("<nobr><b>BEARING SUPPORT<br></b></nobr>");
write("</p>");
write("</v:rect>");
write("</v:group>");
}